/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    AiConfigSettings: typeof import('./src/components/settings/AiConfigSettings.vue')['default']
    AnalyzeMartket: typeof import('./src/components/AnalyzeMartket.vue')['default']
    ClsCalendarTimeLine: typeof import('./src/components/ClsCalendarTimeLine.vue')['default']
    EmbeddedUrl: typeof import('./src/components/EmbeddedUrl.vue')['default']
    Fund: typeof import('./src/components/fund.vue')['default']
    HotEvents: typeof import('./src/components/HotEvents.vue')['default']
    HotStockList: typeof import('./src/components/HotStockList.vue')['default']
    HotTopics: typeof import('./src/components/HotTopics.vue')['default']
    IndustryMoneyRank: typeof import('./src/components/industryMoneyRank.vue')['default']
    IndustryResearchReportList: typeof import('./src/components/IndustryResearchReportList.vue')['default']
    InvestCalendarTimeLine: typeof import('./src/components/InvestCalendarTimeLine.vue')['default']
    KLineChart: typeof import('./src/components/KLineChart.vue')['default']
    LongTigerRankList: typeof import('./src/components/LongTigerRankList.vue')['default']
    Market: typeof import('./src/components/market.vue')['default']
    MinuteProviderSettings: typeof import('./src/components/settings/MinuteProviderSettings.vue')['default']
    MoneyTrend: typeof import('./src/components/moneyTrend.vue')['default']
    NewsList: typeof import('./src/components/newsList.vue')['default']
    RankTable: typeof import('./src/components/rankTable.vue')['default']
    ResearchIndex: typeof import('./src/components/researchIndex.vue')['default']
    ResearchLifecycleTimeline: typeof import('./src/components/ResearchLifecycleTimeline.vue')['default']
    ResearchRecommendations: typeof import('./src/components/researchRecommendations.vue')['default']
    ResearchReport: typeof import('./src/components/researchReport.vue')['default']
    ResearchYield: typeof import('./src/components/researchYield.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectStock: typeof import('./src/components/SelectStock.vue')['default']
    Settings: typeof import('./src/components/settings.vue')['default']
    Stock: typeof import('./src/components/stock.vue')['default']
    Stockhotmap: typeof import('./src/components/stockhotmap.vue')['default']
    StockNoticeList: typeof import('./src/components/StockNoticeList.vue')['default']
    StockResearchReportList: typeof import('./src/components/StockResearchReportList.vue')['default']
    StockSparkLine: typeof import('./src/components/stockSparkLine.vue')['default']
  }
}
