package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedHeader = "// Code generated by go run ./cmd/openapi-contract -write; DO NOT EDIT.\n\n"

type document struct {
	OpenAPI    string              `yaml:"openapi"`
	Paths      map[string]pathItem `yaml:"paths"`
	Components components          `yaml:"components"`
}

type components struct {
	Responses map[string]*response `yaml:"responses"`
	Schemas   map[string]*schema   `yaml:"schemas"`
}

type pathItem struct {
	Get    *operation `yaml:"get"`
	Post   *operation `yaml:"post"`
	Put    *operation `yaml:"put"`
	Patch  *operation `yaml:"patch"`
	Delete *operation `yaml:"delete"`
}

func (p pathItem) operations() map[string]*operation {
	return map[string]*operation{
		"get": p.Get, "post": p.Post, "put": p.Put, "patch": p.Patch, "delete": p.Delete,
	}
}

type operation struct {
	OperationID string               `yaml:"operationId"`
	Responses   map[string]*response `yaml:"responses"`
}

type response struct {
	Ref         string               `yaml:"$ref"`
	Description string               `yaml:"description"`
	Content     map[string]mediaType `yaml:"content"`
}

type mediaType struct {
	Schema *schema `yaml:"schema"`
}

type schema struct {
	Ref        string             `yaml:"$ref"`
	Type       string             `yaml:"type"`
	Format     string             `yaml:"format"`
	Required   []string           `yaml:"required"`
	Properties map[string]*schema `yaml:"properties"`
	AllOf      []*schema          `yaml:"allOf"`
	OneOf      []*schema          `yaml:"oneOf"`
	Enum       []any              `yaml:"enum"`
	Const      any                `yaml:"const"`
	Items      *schema            `yaml:"items"`
	Nullable   bool               `yaml:"nullable"`
}

type route struct {
	Path   string
	Method string
}

func main() {
	var specPath, outputPath, goFiles string
	var write bool
	flag.StringVar(&specPath, "spec", "api/openapi.yaml", "OpenAPI source file")
	flag.StringVar(&outputPath, "output", "frontend/src/services/api-types.generated.ts", "generated TypeScript output")
	flag.StringVar(&goFiles, "go-files", "", "optional comma-separated Go HTTP route files; defaults to web_api*.go")
	flag.BoolVar(&write, "write", false, "write generated output instead of checking it")
	flag.Parse()

	routeFiles, err := resolveGoRouteFiles(goFiles)
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, "openapi contract:", err)
		os.Exit(1)
	}
	if err := run(specPath, outputPath, routeFiles, write); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, "openapi contract:", err)
		os.Exit(1)
	}
}

func resolveGoRouteFiles(configured string) ([]string, error) {
	if strings.TrimSpace(configured) != "" {
		files := make([]string, 0)
		for _, value := range strings.Split(configured, ",") {
			if value = strings.TrimSpace(value); value != "" {
				files = append(files, value)
			}
		}
		if len(files) == 0 {
			return nil, errors.New("go-files did not contain a route file")
		}
		return files, nil
	}
	return discoverGoRouteFiles("web_api*.go")
}

func discoverGoRouteFiles(pattern string) ([]string, error) {
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return nil, fmt.Errorf("discover Go route files: %w", err)
	}
	files := make([]string, 0, len(matches))
	for _, match := range matches {
		if !strings.HasSuffix(match, "_test.go") {
			files = append(files, match)
		}
	}
	sort.Strings(files)
	if len(files) == 0 {
		return nil, errors.New("no production web_api*.go route files found")
	}
	return files, nil
}

func run(specPath, outputPath string, goFiles []string, write bool) error {
	content, err := os.ReadFile(specPath)
	if err != nil {
		return err
	}
	var spec document
	if err := yaml.Unmarshal(content, &spec); err != nil {
		return fmt.Errorf("parse %s: %w", specPath, err)
	}
	var source yaml.Node
	if err := yaml.Unmarshal(content, &source); err != nil {
		return fmt.Errorf("parse YAML nodes in %s: %w", specPath, err)
	}
	if err := validateReferences(&source); err != nil {
		return err
	}
	if err := validateDocument(&spec); err != nil {
		return err
	}
	if err := validateGoRoutes(&spec, goFiles); err != nil {
		return err
	}
	generated, err := generateTypeScript(&spec)
	if err != nil {
		return err
	}
	if write {
		if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(outputPath, generated, 0o644); err != nil {
			return err
		}
		fmt.Printf("wrote %s\n", outputPath)
		return nil
	}

	existing, err := os.ReadFile(outputPath)
	if err != nil {
		return fmt.Errorf("read generated output %s: %w (run with -write)", outputPath, err)
	}
	if !bytes.Equal(normalizeLineEndings(existing), normalizeLineEndings(generated)) {
		return fmt.Errorf("%s is stale (run: go run ./cmd/openapi-contract -write)", outputPath)
	}
	fmt.Printf("OpenAPI contract and %s are consistent\n", outputPath)
	return nil
}

func normalizeLineEndings(content []byte) []byte {
	return bytes.ReplaceAll(content, []byte("\r\n"), []byte("\n"))
}

func validateReferences(root *yaml.Node) error {
	if root == nil || len(root.Content) == 0 {
		return errors.New("OpenAPI YAML is empty")
	}
	var refs []string
	var walk func(*yaml.Node)
	walk = func(node *yaml.Node) {
		if node == nil {
			return
		}
		if node.Kind == yaml.MappingNode {
			for index := 0; index+1 < len(node.Content); index += 2 {
				key, value := node.Content[index], node.Content[index+1]
				if key.Value == "$ref" {
					refs = append(refs, value.Value)
				}
				walk(value)
			}
			return
		}
		for _, child := range node.Content {
			walk(child)
		}
	}
	walk(root)
	for _, ref := range refs {
		if !strings.HasPrefix(ref, "#/") {
			return fmt.Errorf("external OpenAPI reference is not allowed: %q", ref)
		}
		if resolveYAMLPointer(root.Content[0], strings.Split(strings.TrimPrefix(ref, "#/"), "/")) == nil {
			return fmt.Errorf("OpenAPI reference does not resolve: %q", ref)
		}
	}
	return nil
}

func resolveYAMLPointer(node *yaml.Node, segments []string) *yaml.Node {
	current := node
	for _, raw := range segments {
		if current == nil || current.Kind != yaml.MappingNode {
			return nil
		}
		segment := strings.ReplaceAll(strings.ReplaceAll(raw, "~1", "/"), "~0", "~")
		var next *yaml.Node
		for index := 0; index+1 < len(current.Content); index += 2 {
			if current.Content[index].Value == segment {
				next = current.Content[index+1]
				break
			}
		}
		current = next
	}
	return current
}

func validateDocument(spec *document) error {
	if spec == nil || !strings.HasPrefix(spec.OpenAPI, "3.1.") {
		return fmt.Errorf("unsupported OpenAPI version %q; expected 3.1.x", spec.OpenAPI)
	}
	if len(spec.Paths) == 0 || len(spec.Components.Schemas) == 0 {
		return errors.New("paths and components.schemas must not be empty")
	}
	operationIDs := make(map[string]string)
	for path, item := range spec.Paths {
		if !strings.HasPrefix(path, "/") {
			return fmt.Errorf("path must start with '/': %q", path)
		}
		for method, op := range item.operations() {
			if op == nil {
				continue
			}
			if strings.TrimSpace(op.OperationID) == "" {
				return fmt.Errorf("%s %s has no operationId", strings.ToUpper(method), path)
			}
			if previous, exists := operationIDs[op.OperationID]; exists {
				return fmt.Errorf("duplicate operationId %q at %s and %s %s", op.OperationID, previous, strings.ToUpper(method), path)
			}
			operationIDs[op.OperationID] = strings.ToUpper(method) + " " + path
		}
	}
	for name, item := range spec.Components.Schemas {
		if item == nil {
			return fmt.Errorf("schema %s is empty", name)
		}
		if err := validateSchemaRefs(spec, item, "schema "+name); err != nil {
			return err
		}
	}
	return validateInstrumentChartErrorResponses(spec)
}

var instrumentChartErrorResponses = map[string][]string{
	"getInstrumentChart":       {"400"},
	"getInstrumentDrawings":    {"400", "500"},
	"putInstrumentDrawings":    {"400", "409", "500"},
	"deleteInstrumentDrawings": {"400", "404", "409", "500"},
}

func validateInstrumentChartErrorResponses(spec *document) error {
	if spec == nil {
		return errors.New("OpenAPI document is unavailable")
	}
	if err := validateErrorResponseShape(spec.Components.Schemas["ErrorResponse"]); err != nil {
		return fmt.Errorf("components.schemas.ErrorResponse: %w", err)
	}
	operations := make(map[string]*operation)
	for _, item := range spec.Paths {
		for _, op := range item.operations() {
			if op != nil {
				operations[op.OperationID] = op
			}
		}
	}
	for operationID, statuses := range instrumentChartErrorResponses {
		op := operations[operationID]
		if op == nil {
			return fmt.Errorf("instrument chart contract is missing operation %q", operationID)
		}
		for _, status := range statuses {
			item := op.Responses[status]
			if item == nil {
				return fmt.Errorf("operation %s is missing %s ErrorResponse", operationID, status)
			}
			ref, err := responseJSONSchemaRef(spec, item, map[string]bool{})
			if err != nil {
				return fmt.Errorf("operation %s response %s: %w", operationID, status, err)
			}
			if ref != "#/components/schemas/ErrorResponse" {
				return fmt.Errorf("operation %s response %s uses %q; expected #/components/schemas/ErrorResponse", operationID, status, ref)
			}
		}
	}
	return nil
}

func validateErrorResponseShape(item *schema) error {
	if item == nil || item.Type != "object" {
		return errors.New("must be an object")
	}
	errorProperty := item.Properties["error"]
	if errorProperty == nil || errorProperty.Type != "string" {
		return errors.New("must contain an error string property")
	}
	for _, name := range item.Required {
		if name == "error" {
			return nil
		}
	}
	return errors.New("error string property must be required")
}

func responseJSONSchemaRef(spec *document, item *response, visiting map[string]bool) (string, error) {
	if item == nil {
		return "", errors.New("response is empty")
	}
	if item.Ref != "" {
		const prefix = "#/components/responses/"
		if !strings.HasPrefix(item.Ref, prefix) {
			return "", fmt.Errorf("unsupported response reference %q", item.Ref)
		}
		name := strings.TrimPrefix(item.Ref, prefix)
		if name == "" || spec.Components.Responses[name] == nil {
			return "", fmt.Errorf("response reference does not resolve: %q", item.Ref)
		}
		if visiting[name] {
			return "", fmt.Errorf("cyclic response reference %q", item.Ref)
		}
		visiting[name] = true
		defer delete(visiting, name)
		return responseJSONSchemaRef(spec, spec.Components.Responses[name], visiting)
	}
	media, ok := item.Content["application/json"]
	if !ok || media.Schema == nil {
		return "", errors.New("application/json schema is missing")
	}
	return media.Schema.Ref, nil
}

func validateSchemaRefs(spec *document, item *schema, location string) error {
	if item == nil {
		return nil
	}
	if item.Ref != "" {
		name, err := schemaRefName(item.Ref)
		if err != nil {
			return fmt.Errorf("%s: %w", location, err)
		}
		if _, ok := spec.Components.Schemas[name]; !ok {
			return fmt.Errorf("%s references missing schema %q", location, name)
		}
	}
	for name, child := range item.Properties {
		if err := validateSchemaRefs(spec, child, location+"."+name); err != nil {
			return err
		}
	}
	for index, child := range append(append([]*schema{}, item.AllOf...), item.OneOf...) {
		if err := validateSchemaRefs(spec, child, fmt.Sprintf("%s[%d]", location, index)); err != nil {
			return err
		}
	}
	return validateSchemaRefs(spec, item.Items, location+".items")
}

func validateGoRoutes(spec *document, filenames []string) error {
	want := make(map[route]struct{})
	for path, item := range spec.Paths {
		if !isGovernedRoute(path) {
			continue
		}
		for method, op := range item.operations() {
			if op != nil {
				want[route{Path: path, Method: method}] = struct{}{}
			}
		}
	}

	found := make(map[route]struct{})
	for _, filename := range filenames {
		filename = strings.TrimSpace(filename)
		if filename == "" {
			continue
		}
		parsed, err := parser.ParseFile(token.NewFileSet(), filename, nil, 0)
		if err != nil {
			return fmt.Errorf("parse routes in %s: %w", filename, err)
		}
		ast.Inspect(parsed, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok || len(call.Args) < 2 {
				return true
			}
			selector, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || selector.Sel.Name != "HandleFunc" {
				return true
			}
			pattern, ok := stringLiteral(call.Args[0])
			if !ok {
				return true
			}
			method, path := splitRoutePattern(pattern)
			if !isGovernedRoute(path) {
				return true
			}
			if method == "" {
				method = handlerMethod(call.Args[1])
			}
			if method != "" {
				found[route{Path: path, Method: method}] = struct{}{}
			}
			return true
		})
	}

	var missing, undocumented []string
	for item := range want {
		if _, ok := found[item]; !ok {
			missing = append(missing, strings.ToUpper(item.Method)+" "+item.Path)
		}
	}
	for item := range found {
		if _, ok := want[item]; !ok {
			undocumented = append(undocumented, strings.ToUpper(item.Method)+" "+item.Path)
		}
	}
	sort.Strings(missing)
	sort.Strings(undocumented)
	if len(missing) != 0 || len(undocumented) != 0 {
		return fmt.Errorf("Go/OpenAPI route mismatch; missing in Go=%v undocumented in OpenAPI=%v", missing, undocumented)
	}
	return nil
}

func isGovernedRoute(path string) bool {
	return path == "/livez" || path == "/readyz" || strings.HasPrefix(path, "/api/v1/")
}

func splitRoutePattern(pattern string) (string, string) {
	parts := strings.SplitN(strings.TrimSpace(pattern), " ", 2)
	if len(parts) != 2 {
		return "", strings.TrimSpace(pattern)
	}
	method := strings.ToLower(strings.TrimSpace(parts[0]))
	switch method {
	case "get", "post", "put", "patch", "delete":
		return method, strings.TrimSpace(parts[1])
	default:
		return "", strings.TrimSpace(pattern)
	}
}

func stringLiteral(expr ast.Expr) (string, bool) {
	literal, ok := expr.(*ast.BasicLit)
	if !ok || literal.Kind != token.STRING {
		return "", false
	}
	value, err := strconv.Unquote(literal.Value)
	return value, err == nil
}

func handlerMethod(expr ast.Expr) string {
	call, ok := expr.(*ast.CallExpr)
	if !ok || len(call.Args) == 0 {
		return ""
	}
	selector, ok := call.Fun.(*ast.Ident)
	if !ok || selector.Name != "methodHandler" {
		return ""
	}
	method, ok := call.Args[0].(*ast.SelectorExpr)
	if !ok {
		return ""
	}
	switch method.Sel.Name {
	case "MethodGet":
		return "get"
	case "MethodPost":
		return "post"
	case "MethodPut":
		return "put"
	case "MethodPatch":
		return "patch"
	case "MethodDelete":
		return "delete"
	default:
		return ""
	}
}

func generateTypeScript(spec *document) ([]byte, error) {
	var out strings.Builder
	out.WriteString(generatedHeader)
	out.WriteString("export const API_PATHS = {\n")
	type operationPath struct{ id, path string }
	var operations []operationPath
	for path, item := range spec.Paths {
		for _, op := range item.operations() {
			if op != nil {
				operations = append(operations, operationPath{id: op.OperationID, path: path})
			}
		}
	}
	sort.Slice(operations, func(i, j int) bool { return operations[i].id < operations[j].id })
	for _, item := range operations {
		fmt.Fprintf(&out, "  %s: %q,\n", item.id, item.path)
	}
	out.WriteString("} as const\n\n")

	names := make([]string, 0, len(spec.Components.Schemas))
	for name := range spec.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		item := spec.Components.Schemas[name]
		value, err := tsType(item, 0)
		if err != nil {
			return nil, fmt.Errorf("schema %s: %w", name, err)
		}
		fmt.Fprintf(&out, "export type %s = %s\n\n", name, value)
	}
	return []byte(strings.TrimRight(out.String(), "\n") + "\n"), nil
}

func tsType(item *schema, indent int) (string, error) {
	if item == nil {
		return "unknown", nil
	}
	if item.Nullable {
		copy := *item
		copy.Nullable = false
		value, err := tsType(&copy, indent)
		if err != nil {
			return "", err
		}
		return value + " | null", nil
	}
	if item.Ref != "" {
		return schemaRefName(item.Ref)
	}
	if len(item.AllOf) != 0 {
		parts := make([]string, 0, len(item.AllOf))
		for _, child := range item.AllOf {
			value, err := tsType(child, indent)
			if err != nil {
				return "", err
			}
			parts = append(parts, value)
		}
		return strings.Join(parts, " & "), nil
	}
	if len(item.OneOf) != 0 {
		parts := make([]string, 0, len(item.OneOf))
		for _, child := range item.OneOf {
			value, err := tsType(child, indent)
			if err != nil {
				return "", err
			}
			parts = append(parts, value)
		}
		return strings.Join(parts, " | "), nil
	}
	if item.Const != nil {
		return tsLiteral(item.Const), nil
	}
	if len(item.Enum) != 0 {
		parts := make([]string, 0, len(item.Enum))
		for _, value := range item.Enum {
			parts = append(parts, tsLiteral(value))
		}
		return strings.Join(parts, " | "), nil
	}
	switch item.Type {
	case "", "object":
		if len(item.Properties) == 0 {
			return "unknown", nil
		}
		required := make(map[string]struct{}, len(item.Required))
		for _, name := range item.Required {
			required[name] = struct{}{}
		}
		names := make([]string, 0, len(item.Properties))
		for name := range item.Properties {
			names = append(names, name)
		}
		sort.Strings(names)
		var out strings.Builder
		out.WriteString("{\n")
		for _, name := range names {
			value, err := tsType(item.Properties[name], indent+1)
			if err != nil {
				return "", err
			}
			optional := "?"
			if _, ok := required[name]; ok {
				optional = ""
			}
			fmt.Fprintf(&out, "%s%s%s: %s\n", strings.Repeat("  ", indent+1), name, optional, value)
		}
		out.WriteString(strings.Repeat("  ", indent) + "}")
		return out.String(), nil
	case "array":
		value, err := tsType(item.Items, indent)
		if err != nil {
			return "", err
		}
		return "Array<" + value + ">", nil
	case "string":
		return "string", nil
	case "integer", "number":
		return "number", nil
	case "boolean":
		return "boolean", nil
	case "null":
		return "null", nil
	default:
		return "", fmt.Errorf("unsupported schema type %q", item.Type)
	}
}

func schemaRefName(ref string) (string, error) {
	const prefix = "#/components/schemas/"
	if !strings.HasPrefix(ref, prefix) || strings.TrimPrefix(ref, prefix) == "" {
		return "", fmt.Errorf("unsupported schema reference %q", ref)
	}
	return strings.TrimPrefix(ref, prefix), nil
}

func tsLiteral(value any) string {
	switch typed := value.(type) {
	case string:
		return strconv.Quote(typed)
	case bool:
		return strconv.FormatBool(typed)
	case int:
		return strconv.Itoa(typed)
	case int64:
		return strconv.FormatInt(typed, 10)
	case float64:
		return strconv.FormatFloat(typed, 'f', -1, 64)
	default:
		return "unknown"
	}
}
