// Code generated by go run ./cmd/openapi-contract -write; DO NOT EDIT.

export const API_PATHS = {
  connectEventsWebSocket: "/api/v1/events/ws",
  exportConfig: "/api/v1/exports/config",
  exportImage: "/api/v1/exports/image",
  exportMarkdown: "/api/v1/exports/markdown",
  exportWord: "/api/v1/exports/word",
  getAnalysisRun: "/api/v1/research/analysis-run",
  getLegacyHealth: "/healthz",
  getLiveness: "/livez",
  getReadiness: "/readyz",
  getRecommendation: "/api/v1/research/recommendation",
  getSimulatedAccount: "/api/v1/research/account",
  getSystemHealth: "/api/v1/system/health",
  getSystemVersion: "/api/v1/system/version",
  listAnalysisRuns: "/api/v1/research/analysis-runs",
  listRecommendations: "/api/v1/research/recommendations",
} as const

export type AccountOverview = {
  cash: number
  initialCash: number
  netAssetValue: number
  netProfit: number
  netYieldRate: number
  positionValue: number
  positions: Array<Position>
  valuedAt: string
}

export type AnalysisRun = {
  completedAt?: string
  failureReason?: string
  finalReport: string
  marketReport?: string
  modelName?: string
  providerName?: string
  recommendationCount: number
  runId: string
  scheduledFor?: string
  sectorReport?: string
  sourceStatusJson?: string
  startedAt: string
  status: string
  stockReport?: string
}

export type DecisionEvent = {
  decidedAt?: string
  decisionType?: string
  quoteAt?: string
  quotePrice?: number
  reason?: string
}

export type HealthStatus = {
  mode: string
  ok: boolean
  version: string
}

export type LifecycleMessage = {
  content?: string
  createdAt?: string
  phase?: string
  responseId?: string
  role?: string
  sequence?: number
}

export type LivenessStatus = {
  ok: boolean
}

export type Position = {
  buyFees?: number
  currentPrice?: number
  currentPriceAt?: string
  entryAt?: string
  entryPrice?: number
  estimatedSellFees?: number
  netPnl?: number
  netSellValue?: number
  netYieldRate?: number
  quantity?: number
  sellFees?: number
  status?: string
  stockCode?: string
  stockName?: string
}

export type ReadinessStatus = {
  database: boolean
  error?: string
  migrations: boolean
  ready: boolean
  scheduler: boolean
  services: boolean
}

export type Recommendation = {
  activatedAt?: string
  activationCondition?: string
  activationPrice?: number
  aiSummary?: string
  analysisRunId: string
  closePrice?: number
  closedAt?: string
  mainRisk?: string
  netPnl?: number
  netYieldRate?: number
  quantity?: number
  recommendationId: string
  signalAt: string
  sourceRefs?: string
  status: string
  stockCode: string
  stockName: string
  totalFees?: number
}

export type RecommendationDetail = {
  analysis: AnalysisRun
  decisions: Array<DecisionEvent>
  messages: Array<LifecycleMessage>
  position?: Position
  recommendation: Recommendation
  trades: Array<SimulatedTrade>
}

export type SimulatedTrade = {
  executionPrice?: number
  marketPrice?: number
  netCashFlow?: number
  quantity?: number
  side?: string
  totalFees?: number
  tradedAt?: string
}

export type SystemVersionStatus = {
  appVersion: string
  artifactSHA256?: string
  buildTime?: string
  commit?: string
  dirty?: boolean
  mainSchemaVersion: number
  minuteSchemaVersion: number
  readiness: ReadinessStatus
  startedAt?: string
}
