// Code generated by go run ./cmd/openapi-contract -write; DO NOT EDIT.

export const API_PATHS = {
  addGroupStock: "/api/v1/groups/{id}/stocks",
  analyzeWeightedSentiment: "/api/v1/market/sentiment/weighted",
  checkForUpdates: "/api/v1/system/update-check",
  connectEventsWebSocket: "/api/v1/events/ws",
  createGroup: "/api/v1/groups",
  deleteGroup: "/api/v1/groups/{id}",
  exportConfig: "/api/v1/exports/config",
  followFund: "/api/v1/watchlist/funds",
  followStock: "/api/v1/watchlist/stocks",
  getAccountPerformance: "/api/v1/research/account/performance",
  getAnalysisRun: "/api/v1/research/analysis-runs/{id}",
  getCLSCalendar: "/api/v1/market/calendars/cls",
  getGlobalIndexes: "/api/v1/market/indexes/global",
  getIndustryMoneyRank: "/api/v1/market/industries/money-rank",
  getIndustryRank: "/api/v1/market/industries/rank",
  getIndustryResearchReports: "/api/v1/market/industries/{code}/research-reports",
  getInstrumentAuction: "/api/v1/instruments/{code}/auction",
  getInvestmentCalendar: "/api/v1/market/calendars/investment",
  getLiveness: "/livez",
  getLongTigerRank: "/api/v1/market/long-tiger",
  getMarginTrading: "/api/v1/market/margin",
  getMarketBreadth: "/api/v1/market/breadth",
  getMarketDictionary: "/api/v1/market/dictionary",
  getReadiness: "/readyz",
  getRecommendation: "/api/v1/research/recommendations/{id}",
  getRecommendationChart: "/api/v1/research/recommendations/{id}/chart",
  getResearch2Account: "/api/v1/research2/account",
  getResearch2AnalysisRun: "/api/v1/research2/analysis-runs/{id}",
  getResearch2Performance: "/api/v1/research2/account/performance",
  getResearch2Recommendation: "/api/v1/research2/recommendations/{id}",
  getSettings: "/api/v1/settings",
  getSimulatedAccount: "/api/v1/research/account",
  getStockKLine: "/api/v1/stocks/{code}/kline",
  getStockMinuteLine: "/api/v1/stocks/{code}/minute-line",
  getStockMoneyRank: "/api/v1/market/stocks/money-rank",
  getStockMoneyTrend: "/api/v1/market/stocks/{code}/money-trend",
  getStockNotices: "/api/v1/market/stocks/{code}/notices",
  getStockResearchReports: "/api/v1/market/stocks/{code}/research-reports",
  getStockSnapshot: "/api/v1/stocks/{code}/snapshot",
  getSystemInfo: "/api/v1/system/info",
  initializeGroupSort: "/api/v1/groups/initialize-sort",
  listAIConfigs: "/api/v1/ai/configs",
  listAccountCashFlows: "/api/v1/research/account/cash-flows",
  listAnalysisRuns: "/api/v1/research/analysis-runs",
  listFollowedFunds: "/api/v1/watchlist/funds",
  listFollowedStocks: "/api/v1/watchlist/stocks",
  listFuturesPositions: "/api/v1/market/futures/positions",
  listGroups: "/api/v1/groups",
  listHotEvents: "/api/v1/market/hot/events",
  listHotStocks: "/api/v1/market/hot/stocks",
  listHotTopics: "/api/v1/market/hot/topics",
  listIndustryResearchReports: "/api/v1/market/industries/research-reports",
  listInstrumentTrades: "/api/v1/instruments/{code}/trades",
  listMarketFundFlows: "/api/v1/market/fund-flows",
  listRecommendations: "/api/v1/research/recommendations",
  listResearch2AnalysisRuns: "/api/v1/research2/analysis-runs",
  listResearch2Recommendations: "/api/v1/research2/recommendations",
  listStockNotices: "/api/v1/market/stocks/notices",
  listStockResearchReports: "/api/v1/market/stocks/research-reports",
  listTelegraphs: "/api/v1/market/telegraphs",
  queryStocks: "/api/v1/stocks/query",
  refreshRecommendationChart: "/api/v1/research/recommendations/{id}/chart/refresh",
  refreshTelegraphs: "/api/v1/market/telegraphs/refresh",
  removeGroupStock: "/api/v1/groups/{id}/stocks/{code}",
  searchFunds: "/api/v1/funds/search",
  searchStockMaster: "/api/v1/stocks/search",
  shutdownSystem: "/api/v1/system/shutdown",
  startAnalysisRun: "/api/v1/research/analysis-runs",
  testAIConfig: "/api/v1/ai/configs/test",
  testResearch2Email: "/api/v1/research2/email/test",
  unfollowFund: "/api/v1/watchlist/funds/{code}",
  unfollowStock: "/api/v1/watchlist/stocks/{code}",
  updateGroupSort: "/api/v1/groups/{id}/sort",
  updateSettings: "/api/v1/settings",
  updateStockAlarm: "/api/v1/watchlist/stocks/{code}/alarm",
  updateStockPosition: "/api/v1/watchlist/stocks/{code}/position",
  updateStockSort: "/api/v1/watchlist/stocks/{code}/sort",
} as const

export type AIConfigTestRequest = {
  id: number
}

export type AcceptedResponse = {
  accepted: boolean
}

export type AccountCashFlow = {
  amount: number
  createdAt: string
  effectiveAt: string
  flowId: string
  netAssetValueAfter: number
  netAssetValueBefore: number
  sequence: number
  tradingDate: string
  type: "initial_deposit" | "scheduled_deposit"
  unitValueBefore: number
  unitsIssued: number
}

export type AccountOverview = {
  cash: number
  cumulativeCapitalReturn: number
  cumulativeNetContribution: number
  currentPositions: number
  initialCash: number
  netAssetValue: number
  netProfit: number
  netYieldRate: number
  pendingBuys: number
  positionValue: number
  positions: Array<Position>
  timeWeightedReturn: number
  valuedAt: string
}

export type AccountPerformance = {
  cumulativeCapitalReturn: number
  cumulativeNetContribution: number
  curve: Array<AccountPerformancePoint>
  metrics: StrategyPerformanceMetrics
  netAssetValue: number
  netProfit: number
  timeWeightedReturn: number
  unitValue: number
  valuedAt: string
}

export type AccountPerformancePoint = {
  cash: number
  cumulativeNetContribution: number
  netAssetValue: number
  positionValue: number
  snapshotType: "initial_deposit" | "pre_deposit" | "post_deposit" | "daily_close" | "current"
  timeWeightedReturn: number
  tradingDate: string
  unitValue: number
  valuationStatus: string
  valuedAt: string
}

export type AnalysisRun = {
  completedAt?: string
  evidenceProfileVersion?: string
  evidenceSetId?: string
  failureReason?: string
  finalReport: string
  marketReport?: string
  modelAttemptLogJson?: string
  modelName?: string
  providerName?: string
  recommendationCount: number
  runId: string
  scheduledFor?: string
  sectorReport?: string
  sourceStatusJson?: string
  startedAt: string
  status: string
  stockReport?: string
  strategyVersion?: string
}

export type AnalysisRunSummary = {
  completedAt?: string
  failedSourceCount: number
  failureReason?: string
  modelName?: string
  providerName?: string
  recommendationCount: number
  runId: string
  scheduledFor: string
  sourceCount: number
  startedAt: string
  status: string
}

export type AuctionData = {
  assetType: "stock" | "index" | "etf"
  auctionStrength?: number | null
  code: string
  date: string
  finalSnapshot?: AuctionSnapshot
  gapPct?: number | null
  snapshots: Array<AuctionSnapshot>
}

export type AuctionEnvelope = DataEnvelope & {
  data: AuctionData
}

export type AuctionSnapshot = {
  matchedAmount: number
  matchedVolume: number
  price: number
  time: string
  unmatchedSide?: string
  unmatchedVolume?: number | null
}

export type ChartProviderError = {
  message: string
  provider: string
}

export type CommandResponse = {
  message?: string
  ok: boolean
}

export type DataEnvelope = {
  asOf: string
  data: JsonObject | Array<JsonObject>
  errors: Array<DataSourceError>
  evidenceProfile?: string
  evidenceSetId?: string
  fetchedAt: string
  source: string
  sources?: Array<DataSourceState>
  status: "ok" | "partial" | "stale" | "unavailable" | "after_cutoff"
  warnings?: Array<string>
}

export type DataSourceError = {
  code?: string
  message: string
  provider: string
}

export type DataSourceState = {
  asOf?: string
  availableAt?: string
  message?: string
  provider: string
  sourceRef?: string
  status: "ok" | "partial" | "stale" | "unavailable" | "after_cutoff"
}

export type DecisionEvent = {
  aiResponse?: string
  dataStatus?: string
  decidedAt?: string
  decisionType?: string
  eventId?: string
  quoteAt?: string
  quotePrice?: number
  reason?: string
  sourceRefs?: string
}

export type ErrorResponse = {
  error: string
}

export type EvidenceBatch = {
  collectorVersion?: string
  contentHash: string
  cutoffAt: string
  evidenceProfileVersion?: string
  evidenceSetId: string
  frozenAt?: string | null
  items?: Array<EvidenceItem>
  ownerId: string
  ownerType: string
  status: "collecting" | "frozen" | "partial" | "failed"
}

export type EvidenceItem = {
  availableAt?: string
  category: string
  collectedAt: string
  contentHash: string
  entityId?: string
  entityType?: string
  errorMessage?: string
  eventAt?: string
  evidenceItemId: string
  evidenceSetId: string
  sourceId: string
  sourceName: string
  sourceRef?: string
  status: "ok" | "partial" | "stale" | "unavailable" | "after_cutoff"
  summary?: string
}

export type ExportRequest = {
  mode?: "download" | "server"
}

export type ExportResponse = {
  contentBase64?: string
  filename: string
  mime?: string
  mode: "download" | "server"
  path?: string
}

export type FundCodeRequest = {
  fundCode: string
}

export type FundFlowEnvelope = DataEnvelope & {
  data: Array<FundFlowRow>
}

export type FundFlowRow = {
  changePct: number
  code: string
  inAmount: number
  name: string
  netAmount: number
  outAmount: number
}

export type FuturesPositionRow = {
  basis: number
  indexChange: number
  indexClose: number
  longChange: number
  longPosition: number
  netPosition: number
  settlePrice: number
  shortChange: number
  shortPosition: number
  tradeDate: string
}

export type FuturesPositionsData = {
  contractCode: string
  indexCode: string
  rows: Array<FuturesPositionRow>
  variety: "IF" | "IH" | "IC" | "IM"
  varietyName: string
}

export type FuturesPositionsEnvelope = DataEnvelope & {
  data: FuturesPositionsData
}

export type GroupSortRequest = {
  sort: number
}

export type InstrumentID = {
  assetType: "stock" | "index" | "etf"
  code: string
  market: "SH" | "SZ" | "BJ" | "CFFEX"
}

export type JsonObject = unknown

export type LifecycleMessage = {
  content?: string
  createdAt?: string
  phase?: string
  responseId?: string
  role?: string
  sequence?: number
}

export type LifecycleObservation = {
  contentFingerprint?: string
  criticalFailure?: string
  evidenceJson: string
  minuteSummaryJson: string
  modelInvoked: boolean
  observationId: string
  observedAt: string
  phase: string
  quoteJson: string
  recommendationId: string
  sourceStatusJson: string
  status: string
  windowFrom: string
}

export type LivenessStatus = {
  ok: boolean
}

export type MarginData = {
  rows: Array<MarginRow>
  scope: "market" | "security"
}

export type MarginEnvelope = DataEnvelope & {
  data: MarginData
}

export type MarginRow = {
  code?: string
  date: string
  financingBalance: number
  financingBuy: number
  marginBalance: number
  name?: string
  securitiesBalance: number
  securitiesSell: number
}

export type MarketBreadthData = {
  advances: number
  declines: number
  flat: number
  limitDowns: number
  limitUps: number
  medianChangePct: number
  newHighs?: number | null
  newLows?: number | null
  total: number
}

export type MarketBreadthEnvelope = DataEnvelope & {
  data: MarketBreadthData
}

export type Position = {
  buyFees?: number
  currentPrice?: number
  currentPriceAt?: string
  entryAt?: string
  entryPrice?: number
  estimatedSellFees?: number
  netPnl?: number
  netSellValue?: number
  netYieldRate?: number
  quantity?: number
  sellFees?: number
  status?: string
  stockCode?: string
  stockName?: string
}

export type ReadinessStatus = {
  database: boolean
  error?: string
  migrations: boolean
  ready: boolean
  scheduler: boolean
  services: boolean
}

export type Recommendation = {
  activatedAt?: string
  activationCondition?: string
  activationPrice?: number
  aiSummary?: string
  analysisRunId: string
  buyAmount?: number
  buyPrice?: number
  closePrice?: number
  closedAt?: string
  currentAmount?: number
  currentPrice?: number
  dataPauseSeconds?: number
  mainRisk?: string
  netPnl?: number
  netYieldRate?: number
  nextCheckAt?: string
  quantity?: number
  recommendationId: string
  reservedCash?: number
  sellAmount?: number
  sellPrice?: number
  signalAt: string
  sourceRefs?: string
  status: "buy_pending" | "pending" | "active" | "sell_pending" | "invalidated" | "missed_cash" | "missed_untradable" | "closed"
  stockCode: string
  stockName: string
  totalFees?: number
}

export type RecommendationChart = {
  bars: Array<RecommendationChartBar>
  currentNetPnl: number
  currentNetYieldRate: number
  currentPrice: number
  missingSessions: Array<string>
  providerErrors: Array<ChartProviderError>
  quoteAt?: string
  rangeFrom: string
  rangeTo: string
  recommendationId: string
  refreshedAt: string
  sessions: Array<RecommendationChartSession>
  status: "complete" | "partial" | "empty"
  stockCode: string
  stockName: string
  trades: Array<RecommendationChartTrade>
}

export type RecommendationChartBar = {
  amount: number
  at: string
  close: number
  high: number
  low: number
  netPnl: number
  netYieldRate: number
  open: number
  source: string
  volume: number
}

export type RecommendationChartSession = {
  date: string
  previousClose: number
  status: "complete" | "partial" | "missing"
}

export type RecommendationChartTrade = {
  executionPrice: number
  markerAt?: string
  markerSnapped: boolean
  marketPrice: number
  netCashFlow: number
  quantity: number
  side: "buy" | "sell"
  totalFees: number
  tradedAt: string
}

export type RecommendationDetail = {
  activationRemainingSeconds: number
  activationTradingElapsedSeconds: number
  analysis: AnalysisRun
  decisions: Array<DecisionEvent>
  messages: Array<LifecycleMessage>
  observations: Array<LifecycleObservation>
  position?: Position
  recommendation: Recommendation
  trades: Array<SimulatedTrade>
}

export type Research2AccountOverview = {
  cash: number
  initialCash: 12000
  lastValuedAt: string
  netAssetValue: number
  netProfit: number
  openPositions: number
  pendingBuys: number
  positionValue: number
  returnRate: number
}

export type Research2AccountSnapshot = {
  cash: number
  netAssetValue: number
  netProfit: number
  positionValue: number
  returnRate: number
  snapshotId: string
  snapshotType: string
  tradingDate: string
  valuedAt: string
}

export type Research2AnalysisRun = {
  emailAttemptCount?: number
  emailDeliveryStatus?: "pending" | "sending" | "retry_wait" | "sent" | "failed" | "cancelled"
  emailLastError?: string
  emailSentAt?: string | null
  evidenceCutoffAt: string
  evidenceProfileVersion?: string
  evidenceSetId?: string
  failureReason?: string
  generatedAt?: string
  modelAttemptLogJson: string
  modelName?: string
  onTime: boolean
  providerName?: string
  recommendationCount: number
  reportMarkdown: string
  runId: string
  scheduledFor: string
  sourceStatusJson: string
  startedAt: string
  status: "running" | "success" | "no_recommendation" | "failed" | "skipped_non_trading_day" | "missed_window"
  strategyVersion?: string
  tradingDate: string
}

export type Research2AnalysisRunSummary = {
  emailAttemptCount?: number
  emailDeliveryStatus?: "pending" | "sending" | "retry_wait" | "sent" | "failed" | "cancelled"
  emailLastError?: string
  emailSentAt?: string | null
  evidenceCutoffAt: string
  evidenceProfileVersion?: string
  evidenceSetId?: string
  failureReason?: string
  generatedAt?: string
  modelName?: string
  onTime: boolean
  providerName?: string
  recommendationCount: number
  runId: string
  scheduledFor: string
  status: string
  strategyVersion?: string
  tradingDate: string
}

export type Research2Performance = Research2AccountOverview & {
  closedTrades: number
  curve: Array<Research2AccountSnapshot>
  hitFiveCount: number
  hitLimitUpCount: number
  hitMinusThreeCount: number
  lateReports: number
  maxDrawdown?: number | null
  onTimeReports: number
  totalFees: number
  winRate?: number | null
  winningTrades: number
}

export type Research2Recommendation = {
  analysisRunId: string
  buyAt?: string
  buyFees?: number
  buyLower: number
  buyMarketPrice?: number
  buyPrice?: number
  buyUpper: number
  cancelConditions?: string
  catalystScore?: number
  estimatedLotCost?: number
  failureReason?: string
  finalScore: number
  freshCatalyst?: string
  hitFiveBeforeSell?: boolean | null
  hitLimitUpFullDay?: boolean | null
  hitMinusThree?: boolean | null
  late: boolean
  mainRisk?: string
  marketScore?: number
  metricsFinalized: boolean
  netPnl: number
  netYieldRate: number
  oldBackground?: string
  quantData?: string
  quantity: number
  rank: number
  recommendationId: string
  referencePrice: number
  riskDeduction?: number
  sectorScore?: number
  sellAt?: string
  sellFees?: number
  sellMarketPrice?: number
  sellPrice?: number
  signalAt: string
  sourceRefs?: string
  status: "buy_pending" | "active" | "sell_pending" | "closed" | "missed_cash" | "missed_untradable" | "missed_window" | "cancelled_price"
  stockCode: string
  stockName: string
  stockScore?: number
  summary?: string
  targetBuyAt: string
  targetSellAt?: string
}

export type Research2RecommendationDetail = {
  analysis: Research2AnalysisRun
  recommendation: Research2Recommendation
  trades: Array<Research2Trade>
}

export type Research2Trade = {
  commission: number
  executionPrice: number
  marketPrice: number
  netCashFlow: number
  quantity: number
  recommendationId: string
  side: "buy" | "sell"
  slippageAmount: number
  stampDuty: number
  tradeId: string
  tradedAt: string
  transferFee: number
}

export type SentimentRequest = {
  text: string
}

export type SimulatedTrade = {
  executionPrice?: number
  marketPrice?: number
  netCashFlow?: number
  quantity?: number
  side?: string
  totalFees?: number
  tradedAt?: string
}

export type StockAlarmRequest = {
  alarmPrice: number
  value: number
}

export type StockCodeRequest = {
  stockCode: string
}

export type StockPositionRequest = {
  price: number
  volume: number
}

export type StockQueryRequest = {
  words: string
}

export type StockSortRequest = {
  sort: number
}

export type StrategyPerformanceMetrics = {
  averageGainRate: number
  averageHoldingMinutes: number
  averageLossRate: number
  capitalUtilization: number
  closedTrades: number
  industryConcentration: number | null
  industryConcentrationStatus: "available" | "unavailable_no_structured_industry_data"
  maxDrawdown: number
  missedExecutionRate: number
  payoffRatio: number
  sampleLevel: "样本不足" | "初步观察" | "可进行阶段性评价"
  totalFees: number
  turnoverRate: number
  winRate: number
}

export type SystemVersionStatus = {
  appVersion: string
  artifactSHA256?: string
  buildTime?: string
  commit?: string
  dirty?: boolean
  mainSchemaVersion: number
  minuteSchemaVersion: number
  readiness: ReadinessStatus
  startedAt?: string
}

export type TelegraphRefreshRequest = {
  source: string
}

export type TradeTick = {
  amount: number
  price: number
  side?: "buy" | "sell" | "neutral"
  time: string
  volume: number
}

export type TradesData = {
  assetType: "stock" | "index" | "etf"
  code: string
  date: string
  items: Array<TradeTick>
  nextCursor?: string
}

export type TradesEnvelope = DataEnvelope & {
  data: TradesData
}

export type UpdateCheckRequest = {
  flag: number
}
