// Code generated by python -m stock_god.tools.openapi_contract --write; DO NOT EDIT.

export const API_PATHS = {
  analyzeWeightedSentiment: "/api/v1/market/sentiment/weighted",
  connectEventsWebSocket: "/api/v1/events/ws",
  createPredictionReplay: "/api/v1/prediction/replays",
  deleteInstrumentDrawings: "/api/v1/instruments/{code}/drawings",
  etfDetail: "/api/v1/etfs/{code}",
  etfRankings: "/api/v1/etfs/rankings",
  etfSearch: "/api/v1/etfs/search",
  exportConfig: "/api/v1/exports/config",
  exportPredictionAnalysisRunAudit: "/api/v1/prediction/analysis-runs/{id}/audit/export",
  fundRankings: "/api/v1/funds/rankings",
  getCLSCalendar: "/api/v1/market/calendars/cls",
  getGlobalIndexes: "/api/v1/market/indexes/global",
  getIndustryMoneyRank: "/api/v1/market/industries/money-rank",
  getIndustryRank: "/api/v1/market/industries/rank",
  getIndustryResearchReports: "/api/v1/market/industries/{code}/research-reports",
  getInstrumentAuction: "/api/v1/instruments/{code}/auction",
  getInstrumentChart: "/api/v1/instruments/{code}/chart",
  getInstrumentDrawings: "/api/v1/instruments/{code}/drawings",
  getInvestmentCalendar: "/api/v1/market/calendars/investment",
  getLiveness: "/livez",
  getLongTigerRank: "/api/v1/market/long-tiger",
  getMarginTrading: "/api/v1/market/margin",
  getMarketBreadth: "/api/v1/market/breadth",
  getMarketDictionary: "/api/v1/market/dictionary",
  getMarketFundFlowTimeline: "/api/v1/market/fund-flows/{code}/timeline",
  getReadiness: "/readyz",
  getPredictionAccount: "/api/v1/prediction/account",
  getPredictionAnalysisRun: "/api/v1/prediction/analysis-runs/{id}",
  getPredictionAnalysisRunAudit: "/api/v1/prediction/analysis-runs/{id}/audit",
  getPredictionPerformance: "/api/v1/prediction/account/performance",
  getPredictionPortfolioPerformance: "/api/v1/prediction/portfolio/performance",
  getPredictionRecommendation: "/api/v1/prediction/recommendations/{id}",
  getPredictionRecommendationChart: "/api/v1/prediction/recommendations/{id}/chart",
  getPredictionReplay: "/api/v1/prediction/replays/{id}",
  getPredictionSettings: "/api/v1/prediction/settings",
  getSettings: "/api/v1/settings",
  getStockKLine: "/api/v1/stocks/{code}/kline",
  getStockMinuteLine: "/api/v1/stocks/{code}/minute-line",
  getStockMoneyRank: "/api/v1/market/stocks/money-rank",
  getStockMoneyTrend: "/api/v1/market/stocks/{code}/money-trend",
  getStockNotices: "/api/v1/market/stocks/{code}/notices",
  getStockResearchReports: "/api/v1/market/stocks/{code}/research-reports",
  getStockSnapshot: "/api/v1/stocks/{code}/snapshot",
  getSystemInfo: "/api/v1/system/info",
  getTheme: "/api/v1/themes/{id}",
  listPredictionAIConfigs: "/api/v1/prediction/ai/configs",
  listFuturesPositions: "/api/v1/market/futures/positions",
  listHotEvents: "/api/v1/market/hot/events",
  listHotStocks: "/api/v1/market/hot/stocks",
  listHotTopics: "/api/v1/market/hot/topics",
  listIndustryResearchReports: "/api/v1/market/industries/research-reports",
  listInstrumentTrades: "/api/v1/instruments/{code}/trades",
  listMarketFundFlows: "/api/v1/market/fund-flows",
  listMarketHotWords: "/api/v1/market/hot/words",
  listPredictionAnalysisRuns: "/api/v1/prediction/analysis-runs",
  listPredictionRecommendations: "/api/v1/prediction/recommendations",
  listPredictionSlots: "/api/v1/prediction/slots",
  listStockNotices: "/api/v1/market/stocks/notices",
  listStockResearchReports: "/api/v1/market/stocks/research-reports",
  listTelegraphs: "/api/v1/market/telegraphs",
  listThemeCatalysts: "/api/v1/themes/{id}/catalysts",
  listThemeDailySnapshots: "/api/v1/themes/{id}/daily-snapshots",
  listThemes: "/api/v1/themes",
  putInstrumentDrawings: "/api/v1/instruments/{code}/drawings",
  queryStocks: "/api/v1/stocks/query",
  refreshPredictionRecommendationChart: "/api/v1/prediction/recommendations/{id}/chart/refresh",
  refreshTelegraphs: "/api/v1/market/telegraphs/refresh",
  rerunPredictionAnalysisRun: "/api/v1/prediction/analysis-runs/{id}/rerun",
  searchFunds: "/api/v1/funds/search",
  searchStockMaster: "/api/v1/stocks/search",
  shutdownSystem: "/api/v1/system/shutdown",
  testPredictionAIConfig: "/api/v1/prediction/ai/configs/test",
  testPredictionEmail: "/api/v1/prediction/email/test",
  updatePredictionSettings: "/api/v1/prediction/settings",
  updateSettings: "/api/v1/settings",
} as const

export type AIConfigTestRequest = {
  id: number
}

export type AccountCashFlow = {
  amount: number
  createdAt: string
  effectiveAt: string
  flowId: string
  netAssetValueAfter: number
  netAssetValueBefore: number
  sequence: number
  tradingDate: string
  type: "initial_deposit" | "scheduled_deposit"
  unitValueBefore: number
  unitsIssued: number
}

export type AccountOverview = {
  cash: number
  cumulativeCapitalReturn: number
  cumulativeNetContribution: number
  currentPositions: number
  frozen?: boolean
  frozenAt?: string | null
  frozenReason?: string
  initialCash: number
  netAssetValue: number
  netProfit: number
  netYieldRate: number
  pendingBuys: number
  positionValue: number
  positions: Array<Position>
  timeWeightedReturn: number
  valuationStatus: "live" | "partial" | "stored"
  valuedAt: string
}

export type AccountPerformance = {
  cumulativeCapitalReturn: number
  cumulativeNetContribution: number
  curve: Array<AccountPerformancePoint>
  metrics: StrategyPerformanceMetrics
  netAssetValue: number
  netProfit: number
  timeWeightedReturn: number
  unitValue: number
  valuedAt: string
}

export type AccountPerformancePoint = {
  cash: number
  cumulativeNetContribution: number
  netAssetValue: number
  positionValue: number
  snapshotType: "initial_deposit" | "pre_deposit" | "post_deposit" | "daily_close" | "current"
  timeWeightedReturn: number
  tradingDate: string
  unitValue: number
  valuationStatus: string
  valuedAt: string
}

export type AnalysisRun = {
  buyNowCount?: number
  completedAt?: string
  dataProfileVersion?: string
  evidenceProfileVersion?: string
  evidenceSetId?: string
  failureReason?: string
  finalReport: string
  fundingAvailableSlots?: number
  fundingCapitalBuffer?: number
  fundingCash?: number
  fundingDeployableCash?: number
  fundingNetAssetValue?: number
  fundingReservedCash?: number
  leaseExpiresAt?: string
  leaseOwner?: string
  marketReport?: string
  modelAttemptLogJson?: string
  modelName?: string
  opportunities?: Array<BuyOpportunity>
  providerName?: string
  recommendationCount: number
  rejectCount?: number
  runId: string
  scheduledFor?: string
  sectorReport?: string
  sourceStatusJson?: string
  startedAt: string
  status: string
  stockReport?: string
  strategyVersion?: string
  triggerId?: string
  triggerIdsJson?: string
  triggerReason?: string
  triggerSource?: string
  waitCount?: number
}

export type AnalysisRunSummary = {
  buyNowCount?: number
  completedAt?: string
  dataProfileVersion?: string
  failedSourceCount: number
  failureReason?: string
  modelName?: string
  noMatchNewsCount?: number
  providerName?: string
  recommendationCount: number
  rejectCount?: number
  runId: string
  scheduledFor: string
  sourceCount: number
  startedAt: string
  status: string
  strategyVersion?: string
  triggerReason?: string
  triggerSource?: string
  waitCount?: number
}

export type AuctionData = {
  assetType: "stock" | "index" | "etf"
  auctionStrength?: number | null
  code: string
  date: string
  finalSnapshot?: AuctionSnapshot
  gapPct?: number | null
  snapshots: Array<AuctionSnapshot>
}

export type AuctionEnvelope = DataEnvelope & {
  data: AuctionData
}

export type AuctionSnapshot = {
  matchedAmount: number
  matchedVolume: number
  price: number
  time: string
  unmatchedSide?: string
  unmatchedVolume?: number | null
}

export type BuyOpportunity = {
  action: "buy_now" | "wait" | "reject"
  aiSummary?: string
  analysisRunId: string
  createdAt: string
  dataProfileVersion?: string
  decisionQuoteStatus?: "ok" | "stale" | "unavailable" | "invalid" | "legacy-recorded" | "legacy-unavailable"
  expiresAt?: string
  mainRisk?: string
  opportunityId: string
  priceHigh?: number
  priceLow?: number
  quoteAt?: string
  quotePrice?: number
  reanalysisAt?: string
  recommendationId?: string
  requestedAction?: "buy_now" | "wait" | "reject"
  source?: string
  sourceRefs?: string
  status: string
  stockCode: string
  stockName: string
  supersededAt?: string
  supersededByRunId?: string
  timingReason?: string
  updatedAt?: string
  validationReason?: string
}

export type CapitalDeploymentStatus = {
  availableSlots: number
  capitalUtilization: number
  cash: number
  deployableCash: number
  enabled: boolean
  lastTriggeredAt?: string
  netAssetValue: number
  nextEligibleAt?: string
  pendingEventCount: number
  reason: string
  reserveTarget: number
  reservedCash: number
  state: string
  watchingCandidateCount: number
}

export type ChartBar = {
  amount: number
  close: number
  high: number
  low: number
  open: number
  source?: string
  time: string
  volume: number
}

export type ChartData = {
  adjustment: "none" | "qfq" | "hfq"
  bars: Array<ChartBar>
  instrument: InstrumentID
  missingIntervals: Array<ChartMissingInterval>
  period: "1m" | "5m" | "15m" | "30m" | "60m" | "day" | "week" | "month" | "quarter" | "year"
  rangeFrom: string
  rangeTo: string
  timezone: string
}

export type ChartDrawing = {
  createdAt?: string
  deletedAt?: string | null
  id: string
  points: Array<ChartDrawingPoint>
  style?: JsonObject
  type: "measure" | "trend_line" | "ray" | "horizontal_line" | "wave" | "fibonacci_retracement"
  updatedAt?: string
}

export type ChartDrawingDocument = {
  adjustment: "none" | "qfq" | "hfq"
  deletedAt?: string | null
  drawings: Array<ChartDrawing>
  instrument: InstrumentID
  period: "1m" | "5m" | "15m" | "30m" | "60m" | "day" | "week" | "month" | "quarter" | "year"
  revision: number
  updatedAt: string
}

export type ChartDrawingPoint = {
  time: string
  value: number
}

export type ChartEnvelope = DataEnvelope & {
  data: ChartData
}

export type ChartMissingInterval = {
  from: string
  reason: string
  to: string
}

export type ChartProviderError = {
  message: string
  provider: string
}

export type CommandResponse = {
  message?: string
  ok: boolean
}

export type CreateKnowledgeDocumentRequest = {
  contentBase64: string
  filename: string
  mimeType: "text/plain" | "text/markdown" | "application/pdf"
  title?: string
}

export type CreateKnowledgeFromResearchRequest = {
  sourceOwnerId: string
  title?: string
}

export type CreateKnowledgeMemoryCandidateRequest = {
  content?: string
  sourceOwnerId: string
  title?: string
}

export type CreatePredictionReplayRequest = {
  modelConfigId: number
  sourceOwnerId: string
}

export type DataEnvelope = {
  asOf: string
  data: JsonObject | Array<JsonObject>
  errors: Array<DataSourceError>
  evidenceProfile?: string
  evidenceSetId?: string
  fetchedAt: string
  source: string
  sources?: Array<DataSourceState>
  status: "ok" | "partial" | "empty" | "stale" | "unavailable" | "after_cutoff"
  warnings?: Array<string>
}

export type DataSourceError = {
  code?: string
  message: string
  provider: string
}

export type DataSourceState = {
  asOf?: string
  availableAt?: string
  message?: string
  provider: string
  sourceRef?: string
  status: "ok" | "partial" | "stale" | "unavailable" | "after_cutoff"
}

export type DecisionEvent = {
  aiResponse?: string
  dataStatus?: string
  decidedAt?: string
  decisionPolicyVersion?: string
  decisionType?: string
  eventId?: string
  quoteAt?: string
  quotePrice?: number
  reason?: string
  sourceRefs?: string
}

export type ETFDetail = ETFRankingItem & {
  chartInstrument: InstrumentID
  holdings: Array<ETFHolding>
  listDate?: string
  managementFee: number | null
  trackingIndex: string
}

export type ETFDetailEnvelope = DataEnvelope & {
  data: ETFDetail
}

export type ETFHolding = {
  asOf?: string
  code: string
  name: string
  weight?: number | null
}

export type ETFRankingEnvelope = DataEnvelope & {
  data: ETFRankingPage
}

export type ETFRankingItem = {
  amount?: number | null
  category: "broad" | "industry" | "cross_border" | "bond" | "commodity" | "money"
  changeRate?: number | null
  code: string
  market: "SH" | "SZ"
  name: string
  nav?: number | null
  navDate?: string
  netInflow?: number | null
  premiumRate?: number | null
  price?: number | null
  quoteTime?: string
  rank: number
  scale?: number | null
  shares?: number | null
  turnoverRate?: number | null
}

export type ETFRankingPage = {
  category: "all" | "broad" | "industry" | "cross_border" | "bond" | "commodity" | "money"
  items: Array<ETFRankingItem>
  page: number
  pageSize: number
  sort: "changeRate" | "amount" | "turnoverRate" | "premiumRate" | "scale" | "netInflow"
  total: number
}

export type ETFSearchEnvelope = DataEnvelope & {
  data: Array<ETFRankingItem>
}

export type ETFWatchlistItem = ETFWatchlistRequest & {
  createdAt: string
  updatedAt: string
}

export type ETFWatchlistRequest = {
  category: "broad" | "industry" | "cross_border" | "bond" | "commodity" | "money"
  code: string
  market: "SH" | "SZ"
  name: string
}

export type ErrorResponse = {
  error: string
}

export type EvidenceBatch = {
  collectorVersion?: string
  contentHash: string
  cutoffAt: string
  evidenceProfileVersion?: string
  evidenceSetId: string
  frozenAt?: string | null
  items?: Array<EvidenceItem>
  ownerId: string
  ownerType: string
  status: "collecting" | "frozen" | "partial" | "failed"
}

export type EvidenceItem = {
  availableAt?: string
  category: string
  collectedAt: string
  contentHash: string
  entityId?: string
  entityType?: string
  errorMessage?: string
  eventAt?: string
  evidenceItemId: string
  evidenceSetId: string
  sourceId: string
  sourceName: string
  sourceRef?: string
  status: "ok" | "partial" | "stale" | "unavailable" | "after_cutoff"
  summary?: string
}

export type ExportRequest = {
  mode?: "download" | "server"
}

export type ExportResponse = {
  contentBase64?: string
  filename: string
  mime?: string
  mode: "download" | "server"
  path?: string
}

export type FundCodeRequest = {
  fundCode: string
}

export type FundFlowEnvelope = DataEnvelope & {
  data: Array<FundFlowRow>
}

export type FundFlowRow = {
  changePct?: number | null
  code: string
  inAmount?: number | null
  largeNetAmount?: number | null
  mainNetRatio?: number | null
  mediumNetAmount?: number | null
  name: string
  netAmount: number
  outAmount?: number | null
  smallNetAmount?: number | null
  superLargeNetAmount?: number | null
}

export type FundFlowTimelineData = {
  code: string
  name?: string
  points: Array<FundFlowTimelinePoint>
  tradingDate?: string
}

export type FundFlowTimelineEnvelope = DataEnvelope & {
  data: FundFlowTimelineData
}

export type FundFlowTimelinePoint = {
  at: string
  largeNetAmount: number
  mainNetAmount: number
  mediumNetAmount: number
  smallNetAmount: number
  superLargeNetAmount: number
}

export type FundRankingEnvelope = DataEnvelope & {
  data: FundRankingPage
}

export type FundRankingItem = {
  category: "all" | "stock" | "mixed" | "bond" | "index" | "qdii" | "fof"
  code: string
  dayReturn?: number | null
  monthReturn?: number | null
  name: string
  nav?: number | null
  navDate?: string
  oneYearReturn?: number | null
  rank: number
  scale?: number | null
  scaleDate?: string
  sinceInceptionReturn?: number | null
  sixMonthReturn?: number | null
  threeMonthReturn?: number | null
  threeYearReturn?: number | null
  weekReturn?: number | null
  yearToDateReturn?: number | null
}

export type FundRankingPage = {
  category: "all" | "stock" | "mixed" | "bond" | "index" | "qdii" | "fof"
  items: Array<FundRankingItem>
  navDate?: string
  page: number
  pageSize: number
  period: "day" | "week" | "month" | "3m" | "6m" | "1y" | "3y" | "ytd" | "since_inception" | "scale"
  total: number
}

export type FuturesPositionRow = {
  basis: number
  indexChange: number
  indexClose: number
  longChange: number
  longPosition: number
  netPosition: number
  settlePrice: number
  shortChange: number
  shortPosition: number
  tradeDate: string
}

export type FuturesPositionsData = {
  contractCode: string
  indexCode: string
  rows: Array<FuturesPositionRow>
  variety: "IF" | "IH" | "IC" | "IM"
  varietyName: string
}

export type FuturesPositionsEnvelope = DataEnvelope & {
  data: FuturesPositionsData
}

export type GroupSortRequest = {
  sort: number
}

export type HotWordItem = {
  baselineDocumentCount: number
  burstRatio?: number | null
  confidence: "low" | "medium" | "high"
  documentCount: number
  documentShare: number
  growthPct?: number | null
  latestAt: string
  occurrenceCount: number
  rank: number
  representativeNews: Array<HotWordRepresentativeNews>
  score: number
  sourceCount: number
  sources: Array<string>
  word: string
}

export type HotWordRepresentativeNews = {
  excerpt: string
  id: number
  publishedAt: string
  source: string
  title: string
  url?: string
}

export type HotWordsBaseline = {
  available: boolean
  documentCount: number
  effectiveDays: number
  from: string
  mode: "burst" | "coverage_fallback"
  requestedDays: number
  to: string
}

export type HotWordsData = {
  baseline: HotWordsBaseline
  currentDocumentCount: number
  items: Array<HotWordItem>
  sentiment: HotWordsSentiment
  window: HotWordsWindow
}

export type HotWordsEnvelope = DataEnvelope & {
  data: HotWordsData
}

export type HotWordsSentiment = {
  category: number
  description: string
  negativeCount: number
  positiveCount: number
  score: number
}

export type HotWordsWindow = {
  from: string
  hours: number
  to: string
}

export type InstrumentID = {
  assetType: "stock" | "index" | "etf"
  code: string
  market: "SH" | "SZ" | "BJ" | "CFFEX"
}

export type JsonObject = unknown

export type KnowledgeDecisionRequest = {
  decision: "approved" | "rejected"
  reason: string
}

export type KnowledgeDocumentDetail = {
  document: KnowledgeDocumentSummary
  latestVersion: KnowledgeDocumentVersion
}

export type KnowledgeDocumentPage = {
  items: Array<KnowledgeDocumentSummary>
  page: number
  pageSize: number
  total: number
}

export type KnowledgeDocumentSummary = {
  createdAt: string
  documentId: string
  documentType: "text" | "markdown" | "pdf" | "research_report" | "memory"
  latestContentSha256: string
  latestSourceFilename: string
  latestStatus: "draft" | "approved" | "rejected" | "superseded"
  latestVersionNumber: number
  originType: "upload" | "research_report" | "memory_candidate"
  sourceOwnerId: string
  sourceOwnerType: string
  title: string
  updatedAt: string
}

export type KnowledgeDocumentVersion = {
  contentSha256: string
  contentText: string
  createdAt: string
  createdBy: "user" | "system" | "ai"
  decidedAt?: string | null
  decidedBy: string
  decisionReason: string
  documentId: string
  extractionStatus: "pending" | "complete" | "failed"
  mimeType: string
  sourceFilename: string
  status: "draft" | "approved" | "rejected" | "superseded"
  versionId: string
  versionNumber: number
}

export type KnowledgeMemoryCandidate = {
  approvedVersionId?: string
  candidateId: string
  content: string
  contentSha256: string
  createdAt: string
  decidedAt?: string | null
  decidedBy: string
  decisionReason: string
  sourceOwnerId: string
  status: "draft" | "approved" | "rejected"
  title: string
}

export type KnowledgeSearchHit = {
  contentSha256: string
  documentId: string
  excerpt: string
  score: number
  sourceOwnerId: string
  sourceOwnerType: string
  status: "approved"
  title: string
  versionId: string
}

export type KnowledgeVersionDecisionState = {
  approvalReason?: string
  approvedAt?: string
  approvedByActorType?: string
  approvedByUserId?: string
  createdAt: string
  rejectedAt?: string
  rejectedByActorType?: string
  rejectedByUserId?: string
  rejectionReason?: string
  stateId: string
  status: "draft" | "approved" | "rejected" | "superseded"
  updatedAt: string
  versionId: string
}

export type LifecycleMessage = {
  content?: string
  createdAt?: string
  phase?: string
  responseId?: string
  role?: string
  sequence?: number
}

export type LifecycleObservation = {
  contentFingerprint?: string
  criticalFailure?: string
  dataProfileVersion?: string
  evidenceJson: string
  minuteSummaryJson: string
  modelInvoked: boolean
  observationId: string
  observedAt: string
  phase: string
  quoteJson: string
  recommendationId: string
  sourceStatusJson: string
  status: string
  windowFrom: string
}

export type LivenessStatus = {
  ok: boolean
}

export type MarginData = {
  rows: Array<MarginRow>
  scope: "market" | "security"
}

export type MarginEnvelope = DataEnvelope & {
  data: MarginData
}

export type MarginRow = {
  code?: string
  date: string
  financingBalance: number
  financingBuy: number
  marginBalance: number
  name?: string
  securitiesBalance: number
  securitiesSell: number
}

export type MarketBreadthData = {
  advances: number
  declines: number
  flat: number
  limitDowns: number
  limitUps: number
  medianChangePct: number
  newHighs?: number | null
  newLows?: number | null
  total: number
}

export type MarketBreadthEnvelope = DataEnvelope & {
  data: MarketBreadthData
}

export type MinuteWindowSummary = {
  amount: number
  averagePrice: number
  averagePriceMethod: "amount_divided_by_share_volume" | "amount_divided_by_lot_volume_times_100" | "volume_weighted_minute_price_proxy"
  bars: number
  high: number
  low: number
  minutes: number
  returnRate: number
  volume: number
}

export type Position = {
  buyFees?: number
  currentPrice?: number
  currentPriceAt?: string
  entryAt?: string
  entryPrice?: number
  estimatedSellFees?: number
  netPnl?: number
  netSellValue?: number
  netYieldRate?: number
  quantity?: number
  sellFees?: number
  status?: string
  stockCode?: string
  stockName?: string
}

export type PutChartDrawingsRequest = {
  adjustment: "none" | "qfq" | "hfq"
  assetType: "stock" | "index" | "etf"
  drawings: Array<ChartDrawing>
  expectedRevision: number
  market: "SH" | "SZ"
  period: "1m" | "5m" | "15m" | "30m" | "60m" | "day" | "week" | "month" | "quarter" | "year"
}

export type ReadinessStatus = {
  database: boolean
  error?: string
  migrations: boolean
  ready: boolean
  scheduler: boolean
  services: boolean
}

export type Recommendation = {
  activatedAt?: string
  activationCondition?: string
  activationPrice?: number
  aiSummary?: string
  analysisRunId: string
  buyAmount?: number
  buyPrice?: number
  closePrice?: number
  closedAt?: string
  currentAmount?: number
  currentPrice?: number
  dataPauseSeconds?: number
  mainRisk?: string
  netPnl?: number
  netYieldRate?: number
  nextCheckAt?: string
  opportunityId?: string
  quantity?: number
  recommendationId: string
  reservedCash?: number
  sellAmount?: number
  sellPrice?: number
  signalAt: string
  sourceRefs?: string
  status: "buy_pending" | "pending" | "active" | "sell_pending" | "invalidated" | "missed_cash" | "missed_untradable" | "closed"
  stockCode: string
  stockName: string
  totalFees?: number
}

export type RecommendationChart = {
  bars: Array<RecommendationChartBar>
  currentNetPnl: number
  currentNetYieldRate: number
  currentPrice: number
  missingSessions: Array<string>
  providerErrors: Array<ChartProviderError>
  quoteAt?: string
  rangeFrom: string
  rangeTo: string
  recommendationId: string
  refreshedAt: string
  sessions: Array<RecommendationChartSession>
  status: "complete" | "partial" | "empty"
  stockCode: string
  stockName: string
  trades: Array<RecommendationChartTrade>
}

export type RecommendationChartBar = {
  amount: number
  at: string
  close: number
  high: number
  low: number
  netPnl: number
  netYieldRate: number
  open: number
  source: string
  volume: number
}

export type RecommendationChartSession = {
  date: string
  previousClose: number
  status: "complete" | "partial" | "missing"
}

export type RecommendationChartTrade = {
  executionPrice: number
  markerAt?: string
  markerSnapped: boolean
  marketPrice: number
  netCashFlow: number
  quantity: number
  side: "buy" | "sell"
  totalFees: number
  tradedAt: string
}

export type RecommendationDetail = {
  activationRemainingSeconds: number
  activationTradingElapsedSeconds: number
  analysis: AnalysisRun
  decisions: Array<DecisionEvent>
  messages: Array<LifecycleMessage>
  observations: Array<LifecycleObservation>
  position?: Position
  recommendation: Recommendation
  trades: Array<SimulatedTrade>
}

export type PredictionAccountLedgerSnapshot = {
  cash: number
  cumulativeCapitalReturn: number
  cumulativeExternalCapital: number
  netAssetValue: number
  netInternalTransfer: number
  netProfit: number
  positionValue: number
  returnRate: number
  slot?: string
  snapshotId: string
  snapshotType: string
  tradingDate: string
  valuationBasis: string
  valuedAt: string
}

export type PredictionAccountOverview = {
  baselineAt?: string | null
  baselineNetAssetValue?: number
  cash: number
  cumulativeCapitalReturn: number
  cumulativeExternalCapital: number
  initialCash: number
  initialContribution: number
  lastValuedAt: string
  netAssetValue: number
  netInternalTransfer: number
  netProfit: number
  openPositions: number
  pendingBuys: number
  positionValue: number
  returnRate: number
  slot?: string
  topUpContribution: number
  valuationBasis: string
}

export type PredictionAccountSnapshot = {
  cash: number
  netAssetValue: number
  netProfit: number
  positionValue: number
  returnRate: number
  slot?: string
  snapshotId: string
  snapshotType: string
  tradingDate: string
  valuedAt: string
}

export type PredictionAnalysisRun = {
  archiveReason?: string
  attemptNo: number
  chainId?: string
  degraded?: boolean | null
  emailAttemptCount?: number
  emailDeliveryStatus?: "pending" | "sending" | "retry_wait" | "sent" | "failed" | "cancelled"
  emailLastError?: string
  emailSentAt?: string | null
  evidenceCoveragePct?: number | null
  evidenceCutoffAt: string
  evidenceProfileVersion?: string
  evidenceSetId?: string
  evidenceWindowStartAt: string | null
  executionChain?: PredictionExecutionChain
  failureReason?: string
  generatedAt?: string
  modelAttemptLogJson: string
  modelName?: string
  onTime: boolean
  parentRunId?: string
  persistedAt?: string | null
  primaryCount?: number
  providerName?: string
  published?: boolean
  recommendationCount: number
  reportMarkdown: string
  requestedSlots?: number
  runId: string
  scheduledFor: string
  scheduledSlot?: string
  slot?: string
  sourceStatusJson: string
  standbyCount?: number
  startedAt: string
  status: "running" | "success" | "no_recommendation" | "failed" | "skipped_non_trading_day" | "missed_window"
  strategyVersion?: string
  tradingDate: string
  triggerSource?: string
}

export type PredictionAnalysisRunSummary = {
  archiveReason?: string
  attemptNo: number
  chainId?: string
  degraded?: boolean | null
  emailAttemptCount?: number
  emailDeliveryStatus?: "pending" | "sending" | "retry_wait" | "sent" | "failed" | "cancelled"
  emailLastError?: string
  emailSentAt?: string | null
  evidenceCoveragePct?: number | null
  evidenceCutoffAt: string
  evidenceProfileVersion?: string
  evidenceSetId?: string
  evidenceWindowStartAt: string | null
  executionChain?: PredictionExecutionChain
  failureReason?: string
  generatedAt?: string
  modelName?: string
  onTime: boolean
  parentRunId?: string
  persistedAt?: string | null
  primaryCount?: number
  providerName?: string
  published?: boolean
  recommendationCount: number
  requestedSlots?: number
  runId: string
  scheduledFor: string
  scheduledSlot?: string
  slot?: string
  standbyCount?: number
  startedAt: string
  status: string
  strategyVersion?: string
  tradingDate: string
  triggerSource?: string
}

export type PredictionExecutionChain = {
  chainId: string
  completedAt?: string
  createdAt: string
  filledSlots: number
  latestRunId?: string
  rootRunId?: string
  scheduledFor: string
  sellCompletedAt?: string | null
  slot?: string
  startedAt: string
  status: "running" | "completed" | "cutoff" | "exhausted" | "capital_blocked" | "disabled" | "failed"
  stopReason?: string
  targetSlots: number
  tradingDate: string
  updatedAt: string
  winnerRunId?: string
}

export type PredictionOutcomeMetric = {
  count: number
  rate?: number | null
}

export type PredictionPerformance = PredictionAccountOverview & {
  closedTrades: number
  curve: Array<PredictionAccountLedgerSnapshot>
  lateReports: number
  maxDrawdown?: number | null
  onTimeReports: number
  totalFees: number
  winRate?: number | null
  winningTrades: number
}

export type PredictionPortfolioPerformance = {
  boughtTrades: number
  broken: PredictionOutcomeMetric
  classifiedTrades: number
  closedTrades: number
  curve: Array<PredictionPortfolioReturnPoint>
  effectiveAccountCount: number
  from?: string
  incompleteAccountCount: number
  noActivityAccountCount: number
  pendingOutcomeCount: number
  periodReturn?: number | null
  sealed: PredictionOutcomeMetric
  selectedAccountCount: number
  slots: Array<string>
  to?: string
  untouched: PredictionOutcomeMetric
  winRate?: number | null
  winningTrades: number
}

export type PredictionPortfolioReturnPoint = {
  effectiveAccountCount: number
  incompleteAccountCount: number
  returnRate: number
  tradingDate: string
}

export type PredictionRecommendation = {
  analysisRunId: string
  baselineValue?: number
  buyAt?: string
  buyDayLimitAttemptCount: number
  buyDayLimitEvaluatedAt?: string
  buyDayLimitFailureReason?: string
  buyDayLimitOutcome?: "sealed" | "broken" | "untouched"
  buyDayLimitSourceJson: string
  buyDayLimitStatus: "pending" | "complete" | "unavailable"
  buyFees?: number
  buyLower: number
  buyMarketPrice?: number
  buyPrice?: number
  buyUpper: number
  cancelConditions?: string
  catalystScore?: number
  currentPrice?: number
  currentPriceAt?: string
  displaySelectionRank?: number
  displaySelectionRole?: "primary" | "candidate" | ""
  estimatedLotCost?: number
  executionFailureCode?: string
  executionLimitDistancePct?: number | null
  executionLimitPrice?: number
  executionQuoteAt?: string
  executionQuotePrice?: number
  failureReason?: string
  finalScore: number
  freshCatalyst?: string
  late: boolean
  legacySlotException?: boolean
  mainRisk?: string
  marketScore?: number
  netPnl: number
  netYieldRate: number
  oldBackground?: string
  periodPnl?: number
  promotionReason?: string
  quantData?: string
  quantity: number
  recommendationId: string
  referencePrice: number
  replacesRecommendationId?: string
  riskDeduction?: number
  sectorScore?: number
  selectionRank?: number
  selectionRole?: string
  sellAt?: string
  sellFees?: number
  sellMarketPrice?: number
  sellPrice?: number
  signalAt: string
  slot?: string
  sourceRefs?: string
  status: "buy_pending" | "active" | "sell_pending" | "closed" | "analysis_only" | "missed_cash" | "missed_untradable" | "missed_window" | "cancelled_price" | "standby" | "standby_not_used"
  stockCode: string
  stockName: string
  stockScore?: number
  summary?: string
  targetBuyAt: string
  targetSellAt?: string
}

export type PredictionRecommendationDetail = {
  analysis: PredictionAnalysisRun
  recommendation: PredictionRecommendation
  trades: Array<PredictionTrade>
}

export type PredictionSlotStatus = {
  boughtCount: number
  buyStatus: "awaiting_report" | "awaiting_quote" | "bought_full" | "bought_partial" | "no_recommendation" | "cutoff" | "disabled" | "failed" | "processing" | "no_purchase"
  buyTargetCount: number
  label: string
  openPositionCount: number
  pendingBuyCount: number
  reportOnTime?: boolean | null
  reportStatus: "awaiting" | "success" | "no_recommendation" | "failed" | "cutoff" | "disabled"
  sellCompletedAt?: string | null
  slot: string
  status: string
  stopReason?: string
  tradingDate: string
  winnerRunId: string
}

export type PredictionTrade = {
  commission: number
  executionMode?: "live_after_signal" | "recovered_target_minute"
  executionPrice: number
  marketPrice: number
  netCashFlow: number
  priceSource?: string
  priceStale?: boolean
  quantity: number
  quoteAt?: string | null
  recommendationId: string
  side: "buy" | "sell"
  slippageAmount: number
  slot?: string
  stampDuty: number
  tradeId: string
  tradedAt: string
  transferFee: number
}

export type PredictionAuditDetail = {
  availability: "available" | "legacy_unavailable"
  cutoffAt?: string | null
  ownerId: string
  ownerType: "research2" | "replay"
  payloads: Array<PredictionAuditPayload>
  state: PredictionAuditRunState
}

export type PredictionAuditPayload = {
  attempt: number
  callSequence: number
  createdAt: string
  evidenceSha256: string
  evidenceSnapshot: string
  finalPrompt: string
  finalPromptSha256: string
  modelName: string
  modelParameters: JsonObject
  payloadId: string
  phase: string
  providerName: string
  rawResponse: string
  rawResponseSha256: string
  redactionCount: number
  repairLog: string
  repairedResponse: string
  repairedResponseSha256: string
  tools: Array<string>
}

export type PredictionAuditRunState = {
  createdAt: string
  lastError: string
  payloadCount: number
  status: "capturing" | "complete" | "failed" | "legacy_unavailable"
  updatedAt: string
}

export type PredictionReplay = {
  completedAt?: string | null
  createdAt: string
  cutoffAt: string
  diffSummary: JsonObject
  lastError: string
  modelConfigId: number
  replayId: string
  result: string
  resultSha256: string
  sourceOwnerId: string
  startedAt?: string | null
  status: "queued" | "running" | "completed" | "failed"
}

export type PredictionSettings = {
  aiConfigs: Array<JsonObject>
  config: JsonObject
  revision: number
}

export type SentimentRequest = {
  text: string
}

export type SimulatedTrade = {
  executionPrice?: number
  marketPrice?: number
  netCashFlow?: number
  quantity?: number
  side?: string
  totalFees?: number
  tradedAt?: string
}

export type StockAlarmRequest = {
  alarmPrice: number
  value: number
}

export type StockCodeRequest = {
  stockCode: string
}

export type StockPositionRequest = {
  price: number
  volume: number
}

export type StockQueryRequest = {
  words: string
}

export type StockSortRequest = {
  sort: number
}

export type StrategyPerformanceMetrics = {
  averageGainRate: number
  averageHoldingMinutes: number
  averageLossRate: number
  capitalUtilization: number
  closedTrades: number
  industryConcentration: number | null
  industryConcentrationStatus: "available" | "unavailable_no_structured_industry_data"
  maxDrawdown: number
  missedExecutionRate: number
  payoffRatio: number
  sampleLevel: "样本不足" | "初步观察" | "可进行阶段性评价"
  totalFees: number
  turnoverRate: number
  winRate: number
}

export type SystemInfo = {
  content: string
  icon: string
  version: string
}

export type SystemVersionStatus = {
  appVersion: string
  artifactSHA256?: string
  buildTime?: string
  commit?: string
  dirty?: boolean
  mainSchemaVersion: number
  minuteSchemaVersion: number
  readiness: ReadinessStatus
  startedAt?: string
}

export type TelegraphRefreshRequest = {
  source: string
}

export type ThemeCatalyst = {
  catalystEventId: string
  credibilityScore: number
  eventAt: string
  eventType: string
  firstAvailableAt: string
  hasConflict: boolean
  sources: Array<ThemeCatalystSource>
  status: "active" | "disputed" | "retracted" | "expired"
  summary: string
  title: string
}

export type ThemeCatalystSource = {
  availableAt: string
  collectedAt: string
  evidenceItemIds: Array<string>
  publishedAt?: string | null
  sourceClaimId: string
  sourceCredibilityScore: number
  sourceName: string
  sourceRef: string
  stance: "supports" | "contradicts" | "neutral"
  summary: string
}

export type ThemeCatalystSummary = {
  contradicts: number
  hasConflict: boolean
  supports: number
  total: number
}

export type ThemeCatalystsData = {
  items: Array<ThemeCatalyst>
  nextCursor?: string
  themeId: string
  tradeDate: string
}

export type ThemeCatalystsEnvelope = DataEnvelope & {
  data: ThemeCatalystsData
}

export type ThemeConstituent = {
  assetType: "stock" | "index" | "etf" | "fund"
  code: string
  constituentId: string
  contributionScore: number
  market: string
  name: string
  rank: number
  role: string
}

export type ThemeDailySnapshot = {
  catalystCount: number
  constituentCount: number
  cycleNo: number
  frozenAt: string
  heatScore: number
  lifecycleStage: ThemeLifecycleStage
  rank: number
  snapshotId: string
  summary: string
  tradeDate: string
}

export type ThemeDailySnapshotsData = {
  items: Array<ThemeDailySnapshot>
  nextCursor?: string
  themeId: string
}

export type ThemeDailySnapshotsEnvelope = DataEnvelope & {
  data: ThemeDailySnapshotsData
}

export type ThemeDetailData = {
  catalystSummary: ThemeCatalystSummary
  constituents: Array<ThemeConstituent>
  snapshot: ThemeSnapshot | null
  theme: ThemeIdentity
}

export type ThemeDetailEnvelope = DataEnvelope & {
  data: ThemeDetailData
}

export type ThemeIdentity = {
  aliases: Array<string>
  description: string
  name: string
  status: "active" | "archived"
  themeId: string
}

export type ThemeLifecycleStage = "观察" | "发酵" | "加速" | "分歧" | "退潮"

export type ThemeListData = {
  items: Array<ThemeSummary>
  nextCursor?: string
  tradeDate: string
}

export type ThemeListEnvelope = DataEnvelope & {
  data: ThemeListData
}

export type ThemeRepresentativeSecurity = {
  assetType: "stock" | "index" | "etf" | "fund"
  code: string
  market: string
  name: string
  role: string
}

export type ThemeSnapshot = {
  catalystCount: number
  conflictingCatalystCount: number
  constituentCount: number
  cycleNo: number
  frozenAt: string
  heatScore: number
  lifecycleStage: ThemeLifecycleStage
  observedAt: string
  rank: number
  snapshotId: string
  summary: string
  tradeDate: string
}

export type ThemeSummary = {
  aliases: Array<string>
  catalystCount: number
  conflictingCatalystCount: number
  constituentCount: number
  cycleNo: number
  frozenAt: string
  heatScore: number
  lifecycleStage: ThemeLifecycleStage
  name: string
  observedAt: string
  previousLifecycleStage?: ThemeLifecycleStage
  rank: number
  representativeSecurities: Array<ThemeRepresentativeSecurity>
  snapshotId: string
  stageChanged: boolean
  summary: string
  themeId: string
}

export type TradeTick = {
  amount: number
  price: number
  side?: "buy" | "sell" | "neutral"
  time: string
  volume: number
}

export type TradesData = {
  assetType: "stock" | "index" | "etf"
  code: string
  date: string
  items: Array<TradeTick>
  nextCursor?: string
}

export type TradesEnvelope = DataEnvelope & {
  data: TradesData
}
