"""Canonical OpenAPI validation and deterministic frontend types.

The checked-in YAML owns the wire contract. FastAPI's assembled routes are checked
against it; framework-generated request schemas never replace legacy market DTOs.
"""

from __future__ import annotations

import argparse
import copy
import re
from pathlib import Path
from typing import Any

import yaml
from fastapi import routing

from .jsonutil import dumps

METHODS = frozenset({"get", "post", "put", "patch", "delete", "head", "options"})
HEADER = "// Code generated by python -m stock_god.contracts --write; DO NOT EDIT.\n\n"
IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


class ContractError(ValueError):
    pass


class _UniqueLoader(yaml.SafeLoader):
    def construct_mapping(self, node, deep=False):
        keys = [self.construct_object(key, deep=deep) for key, _ in node.value]
        if len(keys) != len(set(keys)):
            raise ContractError("duplicate key in OpenAPI YAML")
        return super().construct_mapping(node, deep=deep)


def resolve(document: dict, reference: str):
    if not isinstance(reference, str) or not reference.startswith("#/"):
        raise ContractError(f"external OpenAPI reference is not allowed: {reference!r}")
    value: Any = document
    try:
        for encoded in reference[2:].split("/"):
            key = encoded.replace("~1", "/").replace("~0", "~")
            value = value[int(key)] if isinstance(value, list) else value[key]
    except (KeyError, IndexError, TypeError, ValueError) as error:
        raise ContractError(f"OpenAPI reference does not resolve: {reference}") from error
    return value


def references(value):
    if isinstance(value, dict):
        if "$ref" in value:
            yield value["$ref"]
        for child in value.values():
            yield from references(child)
    elif isinstance(value, list):
        for child in value:
            yield from references(child)


def operations(document):
    for path, item in document.get("paths", {}).items():
        for method, operation in item.items():
            if method in METHODS:
                yield method.upper(), path, operation


def reachable_components(document):
    """Follow references from live paths, including reusable responses and bodies."""
    live: dict[str, set[str]] = {}
    queue = list(references({key: value for key, value in document.items() if key != "components"}))
    # OpenAPI security requirements refer to schemes by name, not by $ref.
    security = [document.get("security", [])]
    security.extend(operation.get("security", []) for _, _, operation in operations(document))
    for requirement in security:
        for alternative in requirement:
            queue.extend("#/components/securitySchemes/" + name for name in alternative)
    visited = set()
    while queue:
        reference = queue.pop()
        if reference in visited:
            continue
        visited.add(reference)
        target = resolve(document, reference)
        parts = reference.split("/")
        if len(parts) >= 4 and parts[1] == "components":
            category, name = parts[2], parts[3].replace("~1", "/").replace("~0", "~")
            live.setdefault(category, set()).add(name)
            # A reference to one property still makes its enclosing schema public.
            target = document["components"][category][name]
        queue.extend(references(target))
    return live


def prune_components(document):
    result = copy.deepcopy(document)
    live = reachable_components(result)
    result["components"] = {
        category: {name: item for name, item in entries.items() if name in live.get(category, set())}
        for category, entries in result.get("components", {}).items()
        if live.get(category)
    }
    return result


def _response_schema(document, response, seen=None):
    seen = set() if seen is None else seen
    if "$ref" in response:
        reference = response["$ref"]
        if reference in seen:
            raise ContractError("cyclic reusable response reference: " + reference)
        seen.add(reference)
        return _response_schema(document, resolve(document, reference), seen)
    return response.get("content", {}).get("application/json", {}).get("schema", {})


def validate_document(document):
    if not isinstance(document, dict) or not str(document.get("openapi", "")).startswith("3.1."):
        raise ContractError("OpenAPI 3.1.x is required")
    if not document.get("paths") or not document.get("components", {}).get("schemas"):
        raise ContractError("paths and components.schemas must not be empty")
    for reference in references(document):
        resolve(document, reference)
    identifiers = {}
    for method, path, operation in operations(document):
        if not path.startswith("/"):
            raise ContractError("path must start with '/': " + path)
        identity = operation.get("operationId", "")
        if not IDENTIFIER.fullmatch(identity):
            raise ContractError(f"{method} {path} has no valid operationId")
        if identity in identifiers:
            raise ContractError(f"duplicate operationId: {identity}")
        identifiers[identity] = (method, path, operation)
        if not operation.get("responses"):
            raise ContractError(f"{method} {path} has no responses")
    schemas = document["components"]["schemas"]
    for name, schema in schemas.items():
        if not IDENTIFIER.fullmatch(name) or not isinstance(schema, dict):
            raise ContractError("invalid schema: " + name)
        ts_type(schema)
    reachable = reachable_components(document).get("schemas", set())
    unused = set(schemas) - reachable
    if unused:
        raise ContractError("unused schemas: " + ", ".join(sorted(unused)))
    chart_errors = {
        "getInstrumentChart": ("400",),
        "getInstrumentDrawings": ("400", "500"),
        "putInstrumentDrawings": ("400", "409", "500"),
        "deleteInstrumentDrawings": ("400", "404", "409", "500"),
    }
    for identity, statuses in chart_errors.items():
        if identity not in identifiers:
            continue
        for status in statuses:
            response = identifiers[identity][2]["responses"].get(status)
            if (
                not response
                or _response_schema(document, response).get("$ref") != "#/components/schemas/ErrorResponse"
            ):
                raise ContractError(f"{identity} response {status} must use ErrorResponse")
    if any(identity in identifiers for identity in chart_errors):
        error = schemas.get("ErrorResponse", {})
        if (
            error.get("type") != "object"
            or error.get("properties", {}).get("error", {}).get("type") != "string"
            or "error" not in error.get("required", [])
        ):
            raise ContractError("ErrorResponse must require an error string")
    return document


def read_spec(path):
    with Path(path).open(encoding="utf-8") as stream:
        document = yaml.load(stream, Loader=_UniqueLoader)
    return validate_document(document)


def load_spec(root=None):
    root = Path(root) if root is not None else Path(__file__).resolve().parents[2]
    return read_spec(root / "api" / "openapi.yaml")


def ts_type(schema, indent=0):
    if schema is None or schema is True:
        return "unknown"
    if schema is False:
        return "never"
    if schema.get("nullable"):
        return ts_type({key: value for key, value in schema.items() if key != "nullable"}, indent) + " | null"
    if "$ref" in schema:
        reference = schema["$ref"]
        prefix = "#/components/schemas/"
        if not reference.startswith(prefix) or not IDENTIFIER.fullmatch(reference[len(prefix) :]):
            raise ContractError("unsupported TypeScript schema reference: " + reference)
        return reference[len(prefix) :]
    for keyword, separator in (("allOf", " & "), ("oneOf", " | "), ("anyOf", " | ")):
        if schema.get(keyword):
            return separator.join(ts_type(child, indent) for child in schema[keyword])
    if "const" in schema:
        return dumps(schema["const"])
    if schema.get("enum"):
        return " | ".join(dumps(value) for value in schema["enum"])
    kind = schema.get("type", "object")
    if isinstance(kind, list):
        return " | ".join(ts_type({**schema, "type": value}, indent) for value in kind)
    if kind == "object":
        properties = schema.get("properties", {})
        if not properties:
            return "unknown"
        required = set(schema.get("required", []))
        fields = []
        for name, child in sorted(properties.items()):
            key = name if IDENTIFIER.fullmatch(name) else dumps(name)
            optional = "" if name in required else "?"
            fields.append("  " * (indent + 1) + key + optional + ": " + ts_type(child, indent + 1))
        return "{\n" + "\n".join(fields) + "\n" + "  " * indent + "}"
    if kind == "array":
        return "Array<" + ts_type(schema.get("items"), indent) + ">"
    if kind in ("string", "boolean", "null"):
        return kind
    if kind in ("number", "integer"):
        return "number"
    raise ContractError(f"unsupported schema type: {kind}")


def generate_typescript(document):
    validate_document(document)
    output = [HEADER + "export const API_PATHS = {"]
    for identity, path in sorted(
        (operation["operationId"], path) for _, path, operation in operations(document)
    ):
        output.append(f"  {identity}: {dumps(path)},")
    output.append("} as const\n")
    for name, schema in sorted(document["components"]["schemas"].items()):
        output.append(f"export type {name} = {ts_type(schema)}\n")
    return "\n".join(output).rstrip() + "\n"


def governed(path):
    return path in ("/livez", "/readyz") or path.startswith("/api/v1/")


def _route_sets(app):
    http, websockets = {}, set()
    iterator = getattr(routing, "iter_route_contexts", None)
    contexts = iterator(app.routes) if iterator else app.routes
    for context in contexts:
        # Recent FastAPI releases retain included routers lazily. Inspect the same
        # effective routes as FastAPI's OpenAPI builder, including prefix context.
        route = getattr(context, "_effective_route", context)
        path = getattr(route, "path", "")
        if not governed(path):
            continue
        methods = getattr(route, "methods", None)
        if methods is None:
            if path in websockets:
                raise ContractError("duplicate WebSocket route: " + path)
            websockets.add(path)
            continue
        for method in methods:
            key = (method.upper(), path)
            if key in http:
                raise ContractError("duplicate HTTP route: " + " ".join(key))
            http[key] = route
    return http, websockets


def validate_app_routes(app, spec=None):
    spec = load_spec() if spec is None else validate_document(spec)
    expected = {
        (method, path) for method, path, operation in operations(spec) if not operation.get("x-websocket")
    }
    expected_ws = {path for _, path, operation in operations(spec) if operation.get("x-websocket")}
    actual, actual_ws = _route_sets(app)
    missing, extra = expected - actual.keys(), actual.keys() - expected
    if missing or extra or expected_ws != actual_ws:
        raise ContractError(
            f"FastAPI/OpenAPI route mismatch; missing={sorted(missing)}, undocumented={sorted(extra)}, "
            f"missing WebSocket={sorted(expected_ws - actual_ws)}, undocumented WebSocket={sorted(actual_ws - expected_ws)}"
        )
    return actual


def apply_operation_ids(app, spec=None):
    spec = load_spec() if spec is None else spec
    routes = validate_app_routes(app, spec)
    for method, path, operation in operations(spec):
        if operation.get("x-websocket"):
            continue
        routes[(method, path)].operation_id = operation["operationId"]
        original = getattr(routes[(method, path)], "original_route", None)
        if original is not None:
            original.operation_id = operation["operationId"]
    app.openapi_schema = None
    return spec


def check_generated(spec, output_path):
    expected = generate_typescript(spec)
    path = Path(output_path)
    if not path.is_file() or path.read_text(encoding="utf-8") != expected:
        raise ContractError(f"{path} is stale; run python -m stock_god.contracts --write")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, default=Path("api/openapi.yaml"))
    parser.add_argument("--output", type=Path, default=Path("frontend/src/services/api-types.generated.ts"))
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    spec = read_spec(args.spec)
    from .app import create_app

    app = create_app()
    try:
        apply_operation_ids(app, spec)
        if args.write:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(generate_typescript(spec), encoding="utf-8", newline="\n")
        else:
            check_generated(spec, args.output)
    finally:
        app.state.market.close()
        app.state.prediction.database.close()
    print(f"OpenAPI routes and {args.output} are consistent")


if __name__ == "__main__":
    main()
