// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCronTask(arg1) {
  return window['go']['main']['App']['AddCronTask'](arg1);
}

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function AddPrompt(arg1) {
  return window['go']['main']['App']['AddPrompt'](arg1);
}

export function AddStockGroup(arg1, arg2) {
  return window['go']['main']['App']['AddStockGroup'](arg1, arg2);
}

export function AnalyzeSentiment(arg1) {
  return window['go']['main']['App']['AnalyzeSentiment'](arg1);
}

export function AnalyzeSentimentWithFreqWeight(arg1) {
  return window['go']['main']['App']['AnalyzeSentimentWithFreqWeight'](arg1);
}

export function BatchDeleteAIResponseResult(arg1) {
  return window['go']['main']['App']['BatchDeleteAIResponseResult'](arg1);
}

export function ChatWithAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatWithAgent'](arg1, arg2, arg3, arg4);
}

export function CheckStockBaseInfo(arg1) {
  return window['go']['main']['App']['CheckStockBaseInfo'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClsCalendar() {
  return window['go']['main']['App']['ClsCalendar']();
}

export function CreateAgentSession(arg1) {
  return window['go']['main']['App']['CreateAgentSession'](arg1);
}

export function DelPrompt(arg1) {
  return window['go']['main']['App']['DelPrompt'](arg1);
}

export function DeleteAIResponseResult(arg1) {
  return window['go']['main']['App']['DeleteAIResponseResult'](arg1);
}

export function DeleteAgentSession(arg1) {
  return window['go']['main']['App']['DeleteAgentSession'](arg1);
}

export function DeleteAiRecommendStocks(arg1) {
  return window['go']['main']['App']['DeleteAiRecommendStocks'](arg1);
}

export function EMDictCode(arg1) {
  return window['go']['main']['App']['EMDictCode'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function Follow(arg1) {
  return window['go']['main']['App']['Follow'](arg1);
}

export function FollowFund(arg1) {
  return window['go']['main']['App']['FollowFund'](arg1);
}

export function GetAIResponseResult(arg1) {
  return window['go']['main']['App']['GetAIResponseResult'](arg1);
}

export function GetAIResponseResultList(arg1) {
  return window['go']['main']['App']['GetAIResponseResultList'](arg1);
}

export function GetAgentSessionList() {
  return window['go']['main']['App']['GetAgentSessionList']();
}

export function GetAgentSessionMessages(arg1) {
  return window['go']['main']['App']['GetAgentSessionMessages'](arg1);
}

export function GetAiConfigs() {
  return window['go']['main']['App']['GetAiConfigs']();
}

export function GetAiRecommendStocksDateRange() {
  return window['go']['main']['App']['GetAiRecommendStocksDateRange']();
}

export function GetAiRecommendStocksList(arg1) {
  return window['go']['main']['App']['GetAiRecommendStocksList'](arg1);
}

export function GetAiRecommendStocksYieldList(arg1) {
  return window['go']['main']['App']['GetAiRecommendStocksYieldList'](arg1);
}

export function GetAiRecommendYieldDailyOverview(arg1) {
  return window['go']['main']['App']['GetAiRecommendYieldDailyOverview'](arg1);
}

export function GetAiRecommendYieldErrorLogs(arg1) {
  return window['go']['main']['App']['GetAiRecommendYieldErrorLogs'](arg1);
}

export function GetAiRecommendYieldMinuteChart(arg1) {
  return window['go']['main']['App']['GetAiRecommendYieldMinuteChart'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEmailSendLogList(arg1) {
  return window['go']['main']['App']['GetEmailSendLogList'](arg1);
}

export function GetFollowList(arg1) {
  return window['go']['main']['App']['GetFollowList'](arg1);
}

export function GetFollowedFund() {
  return window['go']['main']['App']['GetFollowedFund']();
}

export function GetGroupList() {
  return window['go']['main']['App']['GetGroupList']();
}

export function GetGroupStockList(arg1) {
  return window['go']['main']['App']['GetGroupStockList'](arg1);
}

export function GetHotStrategy() {
  return window['go']['main']['App']['GetHotStrategy']();
}

export function GetIndustryMoneyRankSina(arg1, arg2) {
  return window['go']['main']['App']['GetIndustryMoneyRankSina'](arg1, arg2);
}

export function GetIndustryRank(arg1, arg2) {
  return window['go']['main']['App']['GetIndustryRank'](arg1, arg2);
}

export function GetMoneyRankSina(arg1) {
  return window['go']['main']['App']['GetMoneyRankSina'](arg1);
}

export function GetPromptTemplates(arg1, arg2) {
  return window['go']['main']['App']['GetPromptTemplates'](arg1, arg2);
}

export function GetStockCommonKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockCommonKLine'](arg1, arg2, arg3);
}

export function GetStockKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockKLine'](arg1, arg2, arg3);
}

export function GetStockList(arg1) {
  return window['go']['main']['App']['GetStockList'](arg1);
}

export function GetStockMinutePriceLineData(arg1, arg2) {
  return window['go']['main']['App']['GetStockMinutePriceLineData'](arg1, arg2);
}

export function GetStockMoneyTrendByDay(arg1, arg2) {
  return window['go']['main']['App']['GetStockMoneyTrendByDay'](arg1, arg2);
}

export function GetTelegraphList(arg1) {
  return window['go']['main']['App']['GetTelegraphList'](arg1);
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function GetfundList(arg1) {
  return window['go']['main']['App']['GetfundList'](arg1);
}

export function GlobalStockIndexes() {
  return window['go']['main']['App']['GlobalStockIndexes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HotEvent(arg1) {
  return window['go']['main']['App']['HotEvent'](arg1);
}

export function HotStock(arg1) {
  return window['go']['main']['App']['HotStock'](arg1);
}

export function HotTopic(arg1) {
  return window['go']['main']['App']['HotTopic'](arg1);
}

export function IndustryResearchReport(arg1) {
  return window['go']['main']['App']['IndustryResearchReport'](arg1);
}

export function InitializeGroupSort() {
  return window['go']['main']['App']['InitializeGroupSort']();
}

export function InvestCalendarTimeLine(arg1) {
  return window['go']['main']['App']['InvestCalendarTimeLine'](arg1);
}

export function LongTigerRank(arg1) {
  return window['go']['main']['App']['LongTigerRank'](arg1);
}

export function NewChatStream(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['NewChatStream'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function NewsPush(arg1) {
  return window['go']['main']['App']['NewsPush'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReFleshTelegraphList(arg1) {
  return window['go']['main']['App']['ReFleshTelegraphList'](arg1);
}

export function RemoveGroup(arg1) {
  return window['go']['main']['App']['RemoveGroup'](arg1);
}

export function RemoveStockGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveStockGroup'](arg1, arg2, arg3);
}

export function ResetAgentSession(arg1) {
  return window['go']['main']['App']['ResetAgentSession'](arg1);
}

export function RunMarketSummaryHumanizeCompatFixNow() {
  return window['go']['main']['App']['RunMarketSummaryHumanizeCompatFixNow']();
}

export function SaveAIResponseResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveAIResponseResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveAsMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SaveAsMarkdown'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveWordFile(arg1, arg2) {
  return window['go']['main']['App']['SaveWordFile'](arg1, arg2);
}

export function SearchStock(arg1) {
  return window['go']['main']['App']['SearchStock'](arg1);
}

export function SendDingDingMessage(arg1, arg2) {
  return window['go']['main']['App']['SendDingDingMessage'](arg1, arg2);
}

export function SendDingDingMessageByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDingDingMessageByType'](arg1, arg2, arg3);
}

export function SendLatestAIAnalysisReportNow() {
  return window['go']['main']['App']['SendLatestAIAnalysisReportNow']();
}

export function SendMarketSummaryEmailNow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMarketSummaryEmailNow'](arg1, arg2, arg3, arg4, arg5);
}

export function SendYieldEmailTestMessage() {
  return window['go']['main']['App']['SendYieldEmailTestMessage']();
}

export function SendYieldEmailXLSXNow() {
  return window['go']['main']['App']['SendYieldEmailXLSXNow']();
}

export function SetAlarmChangePercent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAlarmChangePercent'](arg1, arg2, arg3);
}

export function SetCostPriceAndVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCostPriceAndVolume'](arg1, arg2, arg3);
}

export function SetStockAICron(arg1, arg2) {
  return window['go']['main']['App']['SetStockAICron'](arg1, arg2);
}

export function SetStockSort(arg1, arg2) {
  return window['go']['main']['App']['SetStockSort'](arg1, arg2);
}

export function ShareAnalysis(arg1, arg2) {
  return window['go']['main']['App']['ShareAnalysis'](arg1, arg2);
}

export function StartAiRecommendMinuteDownload() {
  return window['go']['main']['App']['StartAiRecommendMinuteDownload']();
}

export function StockNotice(arg1) {
  return window['go']['main']['App']['StockNotice'](arg1);
}

export function StockResearchReport(arg1) {
  return window['go']['main']['App']['StockResearchReport'](arg1);
}

export function SummarizeAgentSessionTitle(arg1) {
  return window['go']['main']['App']['SummarizeAgentSessionTitle'](arg1);
}

export function SummaryStockNews(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SummaryStockNews'](arg1, arg2, arg3, arg4, arg5);
}

export function UnFollow(arg1) {
  return window['go']['main']['App']['UnFollow'](arg1);
}

export function UnFollowFund(arg1) {
  return window['go']['main']['App']['UnFollowFund'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateGroupSort(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroupSort'](arg1, arg2);
}
